services:
  - type: web
    name: el-gadget-api
    runtime: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn scripts.api_local:app --host 0.0.0.0 --port $PORT"
