# -*- coding: utf-8 -*-
"""Posts del blog — contenido informacional que alimenta a las categorías.

Keywords del research SEO-KEYWORDS/blog-*.csv (asignaciones en
MAPA-KEYWORDS.md: una primaria = una URL). Regla: el blog responde
preguntas y linkea al catálogo; NUNCA apunta a las keywords comerciales
de categorías/colecciones (eso sería canibalización).
Los cuerpos admiten HTML (links internos al catálogo).
"""

BLOG_POSTS = {
    'regalos-dia-de-la-madre': {
        'title': 'Día de la Madre 2026 en Argentina: cuándo es y 8 ideas de regalos | El Gadget',
        'h1': 'Día de la Madre 2026: cuándo es y qué regalar',
        'meta': 'El Día de la Madre 2026 en Argentina es el domingo 18 de octubre. Ideas de regalos útiles y originales para todos los presupuestos, con envío a todo el país.',
        'fecha': '2026-07-11',
        'intro': 'En Argentina, el Día de la Madre se celebra el tercer domingo de octubre: en 2026 cae el <strong>domingo 18 de octubre</strong>. Si este año querés llegar con un regalo pensado (y no comprado a las corridas el sábado a la noche), acá van ideas útiles y originales para todos los presupuestos.',
        'secciones': [
            ('Regalos útiles que usa todos los días',
             'Los regalos que más se agradecen son los que se usan: un <a href="/coleccion/vasos-y-botellas-termicas/">vaso térmico</a> para el café o el mate de la mañana, un <a href="/coleccion/organizadores/">organizador</a> que le simplifique la cocina o el placard, o una <a href="/categoria/bazar-y-cocina/">solución de cocina</a> que le ahorre tiempo.'),
            ('Regalos con onda para su espacio',
             'Si lo suyo es la casa: un <a href="/coleccion/lamparas-y-luces-led/">velador LED con diseño</a> para la mesa de luz o un detalle de <a href="/categoria/deco/">deco</a> que renueve el ambiente sin obras. Son regalos que se ven todos los días y siempre la hacen acordar a quien se lo regaló.'),
            ('Para las mamás con estilo',
             'Una <a href="/categoria/accesorios-de-moda/">bandolera o cartera</a> nueva para el día a día, o algún <a href="/categoria/estetica-y-belleza/">accesorio de belleza</a> para su rutina. Y si tu mamá es de las que viven en modo verano, una <a href="/coleccion/mallas-y-trajes-de-bano/">malla nueva</a> anticipa las vacaciones.'),
            ('El tip para no fallar',
             'Compra online con tiempo: el envío llega a todo el país y tenés <strong>cambios hasta 10 días</strong>, así que si el talle o el color no eran los ideales, se cambia sin drama. Mejor pedir el regalo esta semana que pagar el apuro en octubre.'),
        ],
        'faqs': [('¿Cuándo es el Día de la Madre 2026 en Argentina?',
                  'El domingo 18 de octubre de 2026. En Argentina siempre se celebra el tercer domingo de octubre, a diferencia de otros países.'),
                 ('¿Qué regalar si no conozco sus gustos?',
                  'Andá por lo útil: vasos térmicos, organizadores o un velador con diseño funcionan para casi cualquier mamá. Y con cambios hasta 10 días, el riesgo es cero.')],
    },
    'regalos-originales-para-mujeres': {
        'title': 'Regalos Originales para Mujeres: 10 ideas útiles (2026) | El Gadget',
        'h1': 'Regalos originales para mujeres: ideas que no fallan',
        'meta': 'Ideas de regalos originales para mujeres: útiles, con onda y para todos los presupuestos. Cumpleaños, aniversarios o porque sí. Envío a todo el país.',
        'fecha': '2026-07-11',
        'intro': 'Encontrar un regalo original para una mujer que "ya tiene todo" es un clásico problema. La clave no es gastar más: es regalar algo que use, que la sorprenda o que mejore un rato de su día. Estas ideas funcionan para cumpleaños, aniversarios o el simple "vi esto y me acordé de vos".',
        'secciones': [
            ('Para la que vive a mate y café',
             'Un <a href="/coleccion/vasos-y-botellas-termicas/">vaso térmico con tapa</a> la acompaña del escritorio al auto sin que se enfríe el café. Es de esos regalos que se usan todos los días — y cada uso te menciona.'),
            ('Para la que ama su espacio',
             'Un <a href="/coleccion/lamparas-y-luces-led/">velador LED de diseño</a> (los de efecto infinito espejado son los más regalados) o un detalle de <a href="/categoria/deco/">decoración</a> que transforme su rincón favorito.'),
            ('Para la que siempre está en movimiento',
             'Una <a href="/categoria/accesorios-de-moda/">bandolera tejida o riñonera</a> con onda: manos libres, estilo y uso diario garantizado. Mirá los modelos y elegí según su estilo — las fichas tienen fotos reales.'),
            ('Para la organizada (o la que quiere serlo)',
             'Los <a href="/coleccion/organizadores/">organizadores</a> son el regalo sorpresa: nadie los pide, todos los terminan amando. Del placard a la cocina, orden que se nota.'),
        ],
        'faqs': [('¿Qué regalo original conviene si no sé su talle?',
                  'Evitá ropa y andá por accesorios, deco o térmicos: no tienen talle y no fallan. Y si elegís una cartera o malla, hay cambios hasta 10 días.'),
                 ('¿Hacen envíos para regalos a otra dirección?',
                  'Sí: en el checkout ponés la dirección de entrega que quieras y llega a todo el país con seguimiento.')],
    },
    'regalos-originales-para-hombres': {
        'title': 'Regalos Originales para Hombres: 10 ideas útiles (2026) | El Gadget',
        'h1': 'Regalos originales para hombres: ideas que sí va a usar',
        'meta': 'Ideas de regalos originales para hombres: gadgets, térmicos y accesorios útiles para cumpleaños, Día del Padre o Navidad. Envío a todo el país.',
        'fecha': '2026-07-11',
        'intro': 'El problema con regalarle a un hombre no es la falta de opciones: es que la mitad de los regalos terminan en un cajón. La solución es simple — regalá cosas que se usan. Estas ideas funcionan para cumpleaños, Día del Padre, Navidad o amigo invisible.',
        'secciones': [
            ('Para el del mate, el café o la cerveza',
             'El <a href="/coleccion/vasos-y-botellas-termicas/">vaso térmico</a> es el regalo masculino infalible de los últimos años: frío que dura horas para la cerveza del asado, calor para el café del lunes. Hay desde el clásico con tapa hasta el gigante de 1200ml.'),
            ('Para el fierrero (o el desordenado)',
             'El <a href="/coleccion/organizadores/">bolso organizador de baúl</a> transforma el auto: herramientas, compras y equipamiento cada cosa en su lugar. Uno de esos regalos que "no sabía que necesitaba" y termina recomendando.'),
            ('Para el gamer o el tecnológico',
             'Algún <a href="/categoria/electronica/">gadget electrónico</a> útil o una <a href="/coleccion/lamparas-y-luces-led/">lámpara LED de escritorio</a> con ventilador y reloj para el setup. Funcional y con onda.'),
            ('Para el que entrena',
             'Mirá los <a href="/categoria/fitness/">accesorios fitness</a> para entrenar en casa, o directamente una <a href="/coleccion/vasos-y-botellas-termicas/">botella térmica</a> para el gym — hidratación fría hasta la última serie.'),
        ],
        'faqs': [('¿Qué regalar para el Día del Padre?',
                  'En Argentina cae el tercer domingo de junio. Los térmicos, el organizador de baúl y los gadgets de escritorio son los más regalados — todos con envío a domicilio y cambios hasta 10 días.')],
    },
    'como-organizar-el-placard': {
        'title': 'Cómo Organizar el Placard: método simple en 5 pasos | El Gadget',
        'h1': 'Cómo organizar el placard (y que se mantenga ordenado)',
        'meta': 'Método práctico para organizar el placard en 5 pasos: qué sacar, cómo agrupar, dónde van los zapatos y qué organizadores usar para que el orden dure.',
        'fecha': '2026-07-11',
        'intro': 'Organizar el placard no es tirar todo y doblar mejor: es armar un sistema que se mantenga solo. Este método de 5 pasos funciona en placards grandes y chicos, y al final te decimos qué accesorios ayudan de verdad (y cuáles son puro chiche).',
        'secciones': [
            ('Paso 1 y 2: vaciar y decidir',
             'Sacá todo — sí, todo — y armá tres pilas: uso, no uso pero guardo, y se va. Sé honesto: lo que no usaste en un año no lo vas a usar. El placard ordenado empieza con menos cosas, no con más ganchos.'),
            ('Paso 3: agrupar por frecuencia, no por tipo',
             'Lo de todos los días a la altura de los ojos; lo de temporada arriba; lo ocasional abajo. El error clásico es agrupar "todas las camperas juntas" aunque uses una sola: el orden útil sigue tu rutina, no la lógica del catálogo.'),
            ('Paso 4: los zapatos, el jefe final',
             'Los zapatos sueltos destruyen cualquier placard. Un <a href="/coleccion/organizadores/">zapatero abatible</a> los saca del piso y los esconde en el espesor de un cuadro — ideal para recibidores y espacios chicos. Si van dentro del placard, las cajoneras con ruedas aprovechan el piso muerto.'),
            ('Paso 5: sistemas que se mantienen solos',
             'La regla de oro: cada cosa necesita UN lugar obvio. Los <a href="/coleccion/organizadores/">organizadores colgantes y plegables</a> crean esos lugares sin obras ni muebles nuevos. Si guardar algo cuesta más de 5 segundos, el sistema falló — simplificá.'),
        ],
        'faqs': [('¿Cómo organizo un placard chico?',
                  'Verticalidad: colgantes de puerta, estantes divididos y cajoneras apilables. En placards chicos el aire entre estantes es el espacio más desperdiciado.'),
                 ('¿Cómo organizar los zapatos si no tengo lugar?',
                  'Zapatero vertical abatible: ocupa 20cm de profundidad contra la pared. Guarda pares de toda la familia en el espacio de un espejo de pie.')],
    },
    'como-organizar-una-cocina-pequena': {
        'title': 'Cómo Organizar una Cocina Pequeña: 7 trucos que liberan espacio | El Gadget',
        'h1': 'Cómo organizar una cocina pequeña sin obras',
        'meta': 'Trucos concretos para organizar una cocina pequeña: paredes, alturas, mesada libre y los organizadores que sí funcionan. Sin obras ni gastar de más.',
        'fecha': '2026-07-11',
        'intro': 'Una cocina pequeña no necesita más muebles: necesita usar mejor el espacio que ya tiene. Estos trucos van de lo gratis (reacomodar) a lo barato (organizadores puntuales), y todos apuntan a lo mismo: mesada libre y todo a mano.',
        'secciones': [
            ('La mesada es sagrada',
             'La regla número uno: la mesada es para cocinar, no para guardar. Todo lo que vive sobre la mesada tiene que ganarse el lugar. El <a href="/categoria/bazar-y-cocina/">escurridor adhesivo extraíble</a> es el ejemplo perfecto: existe cuando lo necesitás, desaparece cuando no.'),
            ('Usá las paredes y las alturas',
             'El espacio vertical es el gran desperdiciado: <a href="/coleccion/organizadores/">organizadores colgantes</a> para tazas y utensilios, estantes sobre la bacha y ganchos bajo las alacenas. Una pared bien usada equivale a una alacena entera.'),
            ('Secado inteligente',
             'Si el secaplatos clásico te come media mesada, el <a href="/categoria/bazar-y-cocina/">rack de 3 niveles regulable</a> seca la vajilla de toda la familia en la huella de un plato. Altura en vez de superficie: la lógica de toda cocina chica.'),
            ('El cajón de "todo lo demás"',
             'Toda cocina tiene un cajón caótico. Está bien — pero que sea UNO, con divisores. Cuando el caos tiene borde, no se expande.'),
        ],
        'faqs': [('¿Qué es lo primero para ordenar una cocina chica?',
                  'Despejar la mesada. Sacá todo lo que no uses a diario y buscale lugar en altura o pared. El cambio visual es inmediato y motiva el resto.'),
                 ('¿Los organizadores adhesivos aguantan el peso?',
                  'Los de calidad sí, sobre azulejo o superficie lisa y limpia. Cada ficha de producto indica el peso máximo recomendado.')],
    },
    'ideas-para-decorar-una-habitacion': {
        'title': 'Ideas para Decorar una Habitación: 8 cambios de bajo costo | El Gadget',
        'h1': 'Ideas para decorar una habitación sin gastar de más',
        'meta': 'Ideas reales para decorar una habitación: luz cálida, espejos, textiles y detalles con personalidad. Cambios de bajo costo y alto impacto, sin obras.',
        'fecha': '2026-07-11',
        'intro': 'Decorar una habitación no arranca por comprar muebles: arranca por la luz. Después vienen los espejos, los textiles y los detalles. Estas ideas están ordenadas por impacto — las primeras transforman más por menos plata.',
        'secciones': [
            ('1. Cambiá la luz, cambia todo',
             'La luz blanca de techo mata cualquier ambiente. Un <a href="/coleccion/lamparas-y-luces-led/">velador LED cálido</a> en la mesa de luz y alguna luz indirecta crean clima al instante. Los veladores con efecto infinito espejado suman deco de día y magia de noche — por eso son los favoritos en habitaciones juveniles.'),
            ('2. Espejos: el truco de los decoradores',
             'Un <a href="/categoria/deco/">espejo decorativo</a> bien ubicado duplica la luz natural y agranda visualmente el cuarto. Frente a la ventana si querés luz; frente a la puerta, amplitud.'),
            ('3. Detalles con personalidad',
             'Una lámpara con forma divertida, un objeto de <a href="/categoria/deco/">deco</a> que te represente. La habitación genérica se vuelve tuya con dos o tres piezas elegidas, no con veinte.'),
            ('4. El orden ES deco',
             'La habitación más linda se arruina con ropa en la silla. Un <a href="/coleccion/organizadores/">organizador</a> para eso que nunca tiene lugar (el zapatero, la cajonera) es la mejora estética más subestimada.'),
        ],
        'faqs': [('¿Cómo decorar una habitación con poco presupuesto?',
                  'Prioridad: luz cálida (velador LED), un espejo y orden. Con esas tres cosas la habitación cambia más que con un mueble nuevo, y gastás una fracción.'),
                 ('¿Qué luz conviene para una habitación juvenil?',
                  'LED cálida e indirecta: veladores con diseño (efecto infinito, formas) que sumen personalidad. Evitá la luz fría de techo como única fuente.')],
    },
    'como-sacar-pelos-de-mascota-de-la-ropa': {
        'title': 'Cómo Sacar Pelos de Perro y Gato de la Ropa: 6 métodos que funcionan | El Gadget',
        'h1': 'Cómo sacar los pelos de tu mascota de la ropa (y del sillón)',
        'meta': 'Métodos probados para sacar pelos de perro y gato de la ropa, el sillón y el auto: del guante de silicona al truco del lavarropas. Y cómo prevenir.',
        'fecha': '2026-07-11',
        'intro': 'Si tenés perro o gato, los pelos son parte del outfit. Pero hay diferencia entre convivir con algunos pelos y salir de casa hecho un pulóver de angora. Estos métodos funcionan, ordenados del más rápido al más profundo — y al final, el secreto real: la prevención.',
        'secciones': [
            ('El método más rápido: guante de silicona',
             'El <a href="/categoria/accesorios-para-mascotas/">guante removedor de pelos</a> junta con una pasada lo que el rodillo de cinta tarda media hora: los pelos se adhieren a la silicona por estática y se enjuaga bajo la canilla. Sirve para ropa, sillón, manta del auto — y para cepillar directamente a tu mascota.'),
            ('Trucos caseros que suman',
             'Goma de látex o guante de cocina húmedo en pasadas cortas; secarropas 10 minutos con una toalla seca antes de lavar (afloja el pelo); y al lavar, media taza de vinagre blanco en el enjuague relaja las fibras y suelta el pelo pegado.'),
            ('La prevención es el 80%',
             'El pelo que no llega a la ropa no hay que sacarlo: cepillá a tu perro o gato 2-3 veces por semana con un <a href="/categoria/accesorios-para-mascotas/">cepillo o guante para el pelo</a> — en época de muda, a diario. Menos pelo suelto en el animal = menos en tu sillón.'),
            ('Bonus: la zona del comedero',
             'Donde come tu mascota se junta pelo, agua y comida. Una <a href="/categoria/accesorios-para-mascotas/">alfombra para el comedero</a> contiene el desastre en un rectángulo lavable — un truco chico que ahorra limpieza diaria.'),
        ],
        'faqs': [('¿Cómo saco los pelos de gato del sillón?',
                  'Guante de silicona ligeramente húmedo en pasadas firmes hacia un mismo lado: el pelo se junta en rollitos que levantás de una. Para tapizados delicados, aspiradora con cepillo suave antes.'),
                 ('¿Por qué mi perro larga tanto pelo?',
                  'La muda estacional (otoño y primavera) es normal. Si es excesiva fuera de temporada, consultá al veterinario: puede ser alimentación o piel. El cepillado frecuente regula la muda normal.')],
    },
}
