# -*- coding: utf-8 -*-
"""Posts del blog — contenido informacional que alimenta a las categorías.

Keywords del research SEO-KEYWORDS/blog-*.csv (asignaciones en
MAPA-KEYWORDS.md: una primaria = una URL). Regla: el blog responde
preguntas y linkea al catálogo; NUNCA apunta a las keywords comerciales
de categorías/colecciones (eso sería canibalización).
Los cuerpos admiten HTML (links internos al catálogo).
"""

BLOG_POSTS = {
    'regalos-dia-de-la-madre': {
        'imagen': ('/assets/img/blog/regalos-dia-de-la-madre-argentina.jpg', 'Regalos envueltos en papel kraft con cintas amarillas y flores frescas sobre una mesa, listos para el Día de la Madre'),
        'title': 'Día de la Madre 2026 en Argentina: cuándo es y 12 ideas de regalos | El Gadget',
        'h1': 'Día de la Madre 2026: cuándo es y qué regalar',
        'meta': 'El Día de la Madre 2026 en Argentina es el domingo 18 de octubre. 12 ideas de regalos útiles y originales por presupuesto, con envío a todo el país.',
        'fecha': '2026-07-12',
        'intro': 'En Argentina, el Día de la Madre se celebra el tercer domingo de octubre: en 2026 cae el <strong>domingo 18 de octubre</strong>. Si este año querés llegar con un regalo pensado (y no comprado a las corridas el sábado a la noche), acá van 12 ideas útiles y originales, organizadas por tipo de mamá y por presupuesto.',
        'secciones': [
            ('¿Por qué en Argentina se festeja en octubre?',
             'A diferencia de casi todo el mundo (que lo celebra en mayo), Argentina mantiene la fecha de octubre por la tradición católica de la Maternidad de la Virgen, que el calendario litúrgico ubicaba el 11 de octubre. Aunque la Iglesia movió su fecha, la costumbre comercial y familiar quedó: acá, el tercer domingo de octubre es sagrado. Anotalo: <strong>18 de octubre de 2026</strong>.'),
            ('Regalos útiles que va a usar todos los días',
             'Los regalos que más se agradecen son los que entran en la rutina: un <a href="/coleccion/vasos-y-botellas-termicas/">vaso térmico con tapa</a> para el café o el mate de la mañana (el clásico que no falla), una <a href="/coleccion/vasos-y-botellas-termicas/">botella térmica</a> para el agua del día, o esa <a href="/categoria/bazar-y-cocina/">solución de cocina</a> que le ahorre diez minutos diarios. Cada vez que lo use, se va a acordar de quién se lo regaló — ese es el verdadero truco del regalo útil.',
             ('/assets/img/blog/regalo-dia-de-la-madre-vaso-termico-mate.jpg', 'Vaso térmico de acero y mate argentino sobre la mesada de una cocina luminosa, un regalo útil para el Día de la Madre')),
            ('Para la mamá que ama su casa',
             'Si lo suyo es el hogar: un <a href="/coleccion/lamparas-y-luces-led/">velador LED con diseño</a> para la mesa de luz (los de efecto infinito espejado son los más regalados del catálogo), un <a href="/categoria/deco/">espejo decorativo</a> que agrande el living, o un detalle de <a href="/categoria/deco/">deco</a> que renueve el ambiente sin obras. Son regalos que se ven todos los días.',
             ('/assets/img/blog/regalo-mama-velador-led-mesa-de-luz.jpg', 'Velador LED con luz cálida encendido en la mesa de luz de un dormitorio acogedor, idea de regalo para mamá')),
            ('Para la mamá con estilo',
             'Una <a href="/categoria/accesorios-de-moda/">bandolera tejida o cartera</a> nueva para el día a día — liviana, cómoda y con onda — o algún <a href="/categoria/estetica-y-belleza/">accesorio de belleza</a> para su rutina. Y si tu mamá es de las que cuentan los días para las vacaciones, una <a href="/coleccion/mallas-y-trajes-de-bano/">malla nueva</a> es anticipar el verano: con cambios hasta 10 días, el talle no es riesgo.',
             ('prod', r'bandolera tejida')),
            ('Para la mamá organizada (o la que sueña con serlo)',
             'Los <a href="/coleccion/organizadores/">organizadores</a> son el regalo sorpresa: nadie los pide, todas los terminan amando. Un zapatero que libere el recibidor, cajoneras para el placard o el organizador de baúl para el auto. Regalar orden es regalar tiempo — y a una mamá, el tiempo es el regalo más escaso.',
             ('prod', r'zapatero')),
            ('Para la mamá de la mascota de la familia',
             'Si en tu casa el perro o el gato también es hijo: una <a href="/categoria/accesorios-para-mascotas/">alfombra absorbente para el comedero</a> (chau piso mojado), el guante quita-pelos que salva sillones, o un bebedero portátil para los paseos. Regalo para ella, beneficio para toda la casa.',
             ('prod', r'alfombra absorbente')),
            ('Ideas por presupuesto',
             'Con <strong>menos de $20.000</strong>: accesorios de cocina, jaboneras y organizadores chicos, luces LED con sensor. Entre <strong>$20.000 y $40.000</strong>: veladores de diseño, bandoleras, alfombras de diatomita, vasos térmicos. <strong>Más de $40.000</strong>: lámparas de escritorio 3-en-1, mallas, organizadores grandes o armá un combo de dos o tres cosas chicas — el efecto "abrió tres regalos" nunca falla.',
             ('/assets/img/blog/ideas-regalos-dia-de-la-madre-por-presupuesto.jpg', 'Ideas de regalos para el Día de la Madre por presupuesto: bandolera tejida, vaso térmico, velador y caja de regalo con cinta amarilla')),
            ('El tip para no fallar: comprá con tiempo',
             'Comprando online con anticipación tenés envío a todo el país con seguimiento y <strong>cambios hasta 10 días</strong> después de recibido: si el color o el talle no eran los ideales, se cambia sin drama. Pedilo la primera quincena de octubre y llegás sin pagar el apuro. Mirá el <a href="/">catálogo completo</a> o directo las <a href="/categoria/ofertas/">ofertas de la semana</a>.'),
        ],
        'faqs': [('¿Cuándo es el Día de la Madre 2026 en Argentina?',
                  'El domingo 18 de octubre de 2026. En Argentina siempre se celebra el tercer domingo de octubre, a diferencia de la mayoría de los países que lo festejan en mayo.'),
                 ('¿Qué regalar si no conozco sus gustos?',
                  'Andá por lo útil: vasos térmicos, organizadores o un velador con diseño funcionan para casi cualquier mamá. Y con cambios hasta 10 días, el riesgo es cero.'),
                 ('¿Hasta cuándo puedo comprar online para que llegue a tiempo?',
                  'Depende de tu zona: los envíos se calculan en el checkout con su demora estimada. Como regla general, comprá antes del 10 de octubre y llegás cómodo a cualquier punto del país.')],
    },
    'regalos-originales-para-mujeres': {
        'imagen': ('/assets/img/blog/regalos-originales-para-mujeres.jpg', 'Composición de regalos originales para mujeres: bandolera tejida, velador cálido, vaso térmico y caja de regalo con cinta amarilla'),
        'title': 'Regalos Originales para Mujeres: 12 ideas útiles (2026) | El Gadget',
        'h1': 'Regalos originales para mujeres: ideas que no fallan',
        'meta': '12 ideas de regalos originales para mujeres: útiles, con onda y por presupuesto. Para cumpleaños, aniversarios o porque sí. Envío a todo el país.',
        'fecha': '2026-07-12',
        'intro': 'Encontrar un regalo original para una mujer que "ya tiene todo" es un clásico problema. La clave no es gastar más: es regalar algo que use, que la sorprenda o que mejore un rato de su día. Estas 12 ideas funcionan para cumpleaños, aniversarios, el intercambio de fin de año o el simple "vi esto y me acordé de vos".',
        'secciones': [
            ('El error clásico (y cómo evitarlo)',
             'El regalo genérico — la vela, el jabón decorativo, el marco de fotos — dice "cumplí con el compromiso". El regalo que funciona dice "pensé en vos": parte de algo que ella hace todos los días y lo mejora. Por eso las ideas de esta lista están organizadas por rutina, no por producto. Pensá en su día típico y el regalo aparece solo.'),
            ('Para la que vive a mate y café',
             'Un <a href="/coleccion/vasos-y-botellas-termicas/">vaso térmico con tapa</a> la acompaña del escritorio al auto sin que se enfríe el café, y el de vidrio doble pared es el favorito de las cafeteras de especialidad. Si es más de hidratarse, una <a href="/coleccion/vasos-y-botellas-termicas/">botella térmica</a> de acero la sigue al gym, la facu o la oficina. Es de esos regalos que se usan a diario — y cada uso te menciona.',
             ('/assets/img/blog/regalo-original-mujer-vaso-termico-cafe.jpg', 'Vaso de vidrio doble pared con café con leche sobre un escritorio luminoso, regalo original para mujeres que aman el café')),
            ('Para la que ama su espacio',
             'Un <a href="/coleccion/lamparas-y-luces-led/">velador LED de diseño</a> (los de efecto infinito espejado son los más regalados), un <a href="/categoria/deco/">espejo decorativo</a> que duplique la luz de su ambiente favorito, o un detalle de <a href="/categoria/deco/">deco con personalidad</a>. La que disfruta su casa valora más un objeto que la mejore que cualquier cosa para "guardar".'),
            ('Para la que siempre está en movimiento',
             'Una <a href="/categoria/accesorios-de-moda/">bandolera tejida</a> con onda para salir liviana, una riñonera urbana para el día largo, o una cartera con más lugar. Manos libres, estilo y uso garantizado. Las fichas tienen fotos reales y medidas — elegí según su estilo, no según el apuro.',
             ('/assets/img/blog/regalo-mujer-bandolera-tejida.jpg', 'Bandolera tejida al crochet y riñonera urbana colgadas de un perchero de madera, regalos originales para mujeres en movimiento')),
            ('Para la organizada (o la que quiere serlo)',
             'Los <a href="/coleccion/organizadores/">organizadores</a> son el regalo sorpresa: nadie los pide, todas los terminan amando. Cajoneras para el placard, colgantes para la cocina, el zapatero que libera el recibidor. Regalar orden es regalar espacio mental.'),
            ('Para la que ya está pensando en el verano',
             'Una <a href="/coleccion/mallas-y-trajes-de-bano/">malla nueva</a> — enteriza que estiliza o bikini de tiro alto — anticipa las vacaciones en cualquier mes del año. Con la tabla de talles de cada ficha y cambios hasta 10 días, es un regalo mucho menos arriesgado de lo que parece. Y si tiene pileta, un <a href="/coleccion/inflables-para-pileta/">inflable gigante</a> es la sorpresa divertida.',
             ('/assets/img/blog/regalo-mujer-malla-verano.jpg', 'Malla enteriza sobre toalla de rayas con sombrero de paja y anteojos de sol, regalo de verano para mujeres')),
            ('Ideas por presupuesto',
             'Con <strong>menos de $20.000</strong>: accesorios de belleza, organizadores chicos, luces LED. Entre <strong>$20.000 y $40.000</strong>: bandoleras, veladores de diseño, vasos térmicos, alfombras de diatomita para el baño. <strong>Más de $40.000</strong>: mallas, lámparas 3-en-1 de escritorio, o un combo de varias cosas chicas que se abren una por una.'),
        ],
        'faqs': [('¿Qué regalo original conviene si no sé su talle?',
                  'Evitá ropa y andá por accesorios, deco o térmicos: no tienen talle y no fallan. Y si elegís una cartera o malla, hay cambios hasta 10 días.'),
                 ('¿Hacen envíos para regalos a otra dirección?',
                  'Sí: en el checkout ponés la dirección de entrega que quieras y llega a todo el país con seguimiento por email.'),
                 ('¿Qué regalar para un cumpleaños de último momento?',
                  'Elegí algo de su rutina diaria (térmico, velador, bandolera) y comprá ya: el envío tiene demora estimada visible en el checkout. Para zonas cercanas suele llegar en pocos días.')],
    },
    'regalos-originales-para-hombres': {
        'imagen': ('/assets/img/blog/regalos-originales-para-hombres.jpg', 'Regalos originales para hombres sobre fondo gris: vaso térmico de acero, gadget, lámpara de escritorio y caja kraft con cinta amarilla'),
        'title': 'Regalos Originales para Hombres: 12 ideas útiles (2026) | El Gadget',
        'h1': 'Regalos originales para hombres: ideas que sí va a usar',
        'meta': '12 ideas de regalos originales para hombres: gadgets, térmicos y accesorios útiles para cumpleaños, Día del Padre o Navidad. Envío a todo el país.',
        'fecha': '2026-07-12',
        'intro': 'El problema con regalarle a un hombre no es la falta de opciones: es que la mitad de los regalos terminan en un cajón. La solución es simple — regalá cosas que se usan. Estas 12 ideas funcionan para cumpleaños, Día del Padre, Navidad o amigo invisible, organizadas por tipo de tipo.',
        'secciones': [
            ('La regla de oro: utilidad primero',
             'Los hombres son el público más fácil de conformar y el más difícil de sorprender. El truco: no busques "el regalo perfecto", buscá el objeto que mejora algo que él ya hace — tomar mate, ordenar el auto, armar su escritorio. La sorpresa no está en el objeto raro sino en que alguien haya mirado su rutina con atención.'),
            ('Para el del mate, el café o la cerveza',
             'El <a href="/coleccion/vasos-y-botellas-termicas/">vaso térmico</a> es el regalo masculino infalible de los últimos años: frío que dura horas para la cerveza del asado, calor para el café del lunes. Hay desde el clásico Stanley de 480ml con tapa hasta el gigante de 1200ml con agarre que banca el día entero. Si ya tiene vaso, la <a href="/coleccion/vasos-y-botellas-termicas/">botella térmica</a> de acero es el paso dos.',
             ('/assets/img/blog/regalo-hombre-vaso-termico-asado.jpg', 'Vaso térmico de acero junto a la parrilla de un quincho argentino al atardecer, regalo para hombres')),
            ('Para el fierrero (o el desordenado)',
             'El <a href="/coleccion/organizadores/">bolso organizador de baúl</a> transforma el auto: herramientas, compras y equipamiento, cada cosa en su lugar y sin ruidos en cada curva. Es uno de esos regalos que "no sabía que necesitaba" y termina recomendando a los amigos. Sumale el zapatero vertical si su placard es zona de guerra.',
             ('/assets/img/blog/regalo-hombre-organizador-baul-auto.jpg', 'Baúl de auto ordenado con bolso organizador plegable con herramientas y elementos de viaje')),
            ('Para el gamer o el tecnológico',
             'Algún <a href="/categoria/electronica/">gadget electrónico</a> útil o la <a href="/coleccion/lamparas-y-luces-led/">lámpara LED de escritorio</a> con ventilador USB y reloj — el 3-en-1 del home office y el setup gamer. Funcional, con onda, y sin el riesgo de regalarle un periférico que ya tiene mejor.',
             ('prod', r'lampara led escritorio|l[áa]mpara led escritorio')),
            ('Para el que entrena (o dice que va a empezar)',
             'Los <a href="/categoria/fitness/">accesorios fitness</a> para entrenar en casa eliminan la excusa del gimnasio, y una <a href="/coleccion/vasos-y-botellas-termicas/">botella térmica</a> mantiene el agua helada hasta la última serie. Regalo doble mensaje: te apoyo, y no tenés más excusas.',
             ('prod', r'botella t[ée]rmica')),
            ('Para el papá perro (o gato)',
             'Si su mascota es su copiloto: el <a href="/categoria/accesorios-para-mascotas/">guante quita-pelos</a> que salva el asiento del auto y el sillón, el bebedero portátil para las salidas, o la alfombra absorbente para la zona del comedero. Práctico y con puntos extra de ternura.',
             ('prod', r'guante removedor|guante.*pelos')),
            ('Ideas por presupuesto',
             'Con <strong>menos de $20.000</strong>: gadgets chicos, luces LED con sensor, accesorios para el auto. Entre <strong>$20.000 y $40.000</strong>: vasos térmicos, organizadores de baúl, accesorios fitness. <strong>Más de $40.000</strong>: lámparas de escritorio 3-en-1, botellas térmicas grandes, o el combo térmico + organizador que nunca falla.'),
            ('¿Cuándo es el Día del Padre?',
             'En Argentina, el <strong>tercer domingo de junio</strong>. Si llegaste tarde este año, anotalo para el próximo — o mejor: regalale algo hoy "porque sí". Los regalos sin fecha son los que más se recuerdan. Mirá las <a href="/categoria/ofertas/">ofertas de la semana</a> para aprovechar el momento.'),
        ],
        'faqs': [('¿Qué regalar para el Día del Padre?',
                  'En Argentina cae el tercer domingo de junio. Los térmicos, el organizador de baúl y los gadgets de escritorio son los más regalados — todos con envío a domicilio y cambios hasta 10 días.'),
                 ('¿Qué le regalo a un hombre que dice que no necesita nada?',
                  'El que "no necesita nada" es el candidato ideal para el regalo de rutina mejorada: un térmico mejor que el que usa, orden para el auto que ya tiene. No es necesitar: es mejorar lo que ya hace.'),
                 ('¿Puedo mandar el regalo directo a su casa?',
                  'Sí: en el checkout cargás su dirección y le llega con seguimiento. Ideal para sorpresas a distancia.')],
    },
    'como-limpiar-termo-acero-inoxidable': {
        'imagen': ('/assets/img/blog/como-limpiar-termo-acero-inoxidable.jpg', 'Termo de acero inoxidable destapado junto a cepillo para botellas, vinagre blanco y bicarbonato sobre la mesada'),
        'title': 'Cómo Limpiar un Termo de Acero Inoxidable por Dentro (sarro y olores) | El Gadget',
        'h1': 'Cómo limpiar un termo de acero inoxidable por dentro',
        'meta': 'Guía completa para limpiar un termo de acero inoxidable por dentro: sacar el sarro, eliminar olores y qué NO usar nunca. Métodos caseros que funcionan.',
        'fecha': '2026-07-13',
        'intro': 'El termo de acero inoxidable es de esos objetos que usamos todos los días y limpiamos… cuando nos acordamos. El problema: el sarro y el olor a mate viejo se acumulan por dentro, donde la esponja no llega. La buena noticia es que limpiarlo bien lleva 10 minutos con cosas que ya tenés en la cocina — y hay dos o tres errores que pueden arruinarlo para siempre.',
        'secciones': [
            ('La limpieza básica (una vez por semana)',
             'Agua bien caliente, unas gotas de detergente, tapá y agitá 30 segundos. Para llegar al fondo, un <a href="/categoria/bazar-y-cocina/">cepillo flexible para botellas</a> hace la diferencia: las cerdas de silicona limpian las paredes sin rayar el acero. Enjuagá dos veces y dejá secar SIEMPRE destapado y boca abajo — el 80% de los olores nacen de guardarlo húmedo y cerrado.',
             ('prod', r'cepillo flexible')),
            ('Cómo sacar el sarro del termo',
             'El sarro (esas manchas blancas o marrones del fondo) sale con vinagre blanco: llená un tercio del recipiente con vinagre, completá con agua caliente, dejá actuar 30-60 minutos y cepillá el fondo. Para sarro rebelde, el combo bicarbonato + vinagre: dos cucharadas de bicarbonato, medio vaso de vinagre, dejalo burbujear destapado 15 minutos, cepillo y enjuague. El acero inoxidable queda como nuevo sin ningún producto agresivo.',
             ('/assets/img/blog/limpiar-sarro-termo-vinagre-bicarbonato.jpg', 'Interior de un termo de acero inoxidable con espuma de bicarbonato y vinagre burbujeando')),
            ('Cómo quitar el olor de un termo',
             'Si el termo quedó con olor a mate de ayer (o a café de la semana pasada): bicarbonato y agua caliente toda la noche, destapado. Para olores persistentes, el truco del arroz: un puñado de arroz crudo, un chorro de vinagre y agua tibia — tapá y agitá fuerte un minuto; el arroz hace de esponja abrasiva suave donde nada más llega. Enjuague doble y secado destapado.'),
            ('Lo que NUNCA hay que hacerle a un termo de acero',
             'cuatro errores fatales: lavandina (pica el acero inoxidable y deja olor químico), esponja de acero o virulana por dentro (raya y ahí anida el sarro), lavavajillas (el calor del ciclo puede arruinar el vacío térmico del doble pared) y meterlo al freezer (mismo problema, al revés). Si el tuyo dejó de mantener la temperatura después de un lavavajillas, ya sabés qué pasó.'),
            ('¿Por qué mi termo ya no mantiene el calor?',
             'Un termo de doble pared funciona por el vacío entre sus paredes. Si recibió un golpe fuerte, pasó por el lavavajillas o el freezer, ese vacío puede perderse — y no tiene arreglo: se convierte en una botella común. La prueba: servile agua caliente; si la pared exterior se calienta, perdió el vacío. En ese caso, es momento de renovarlo — mirá los <a href="/coleccion/vasos-y-botellas-termicas/">vasos y botellas térmicas</a> del catálogo, con doble pared de acero real.'),
            ('La rutina que lo hace durar años',
             'Enjuague con agua caliente después de cada uso (30 segundos), lavado con detergente y cepillo una vez por semana, vinagre contra el sarro una vez por mes si tomás mate o café a diario, y secado siempre destapado. Con esa rutina mínima, uno de buena calidad dura años manteniendo el frío y el calor como el primer día.',
             ('/assets/img/blog/secar-termo-destapado-boca-abajo.jpg', 'Termos y vaso térmico de acero secándose boca abajo destapados sobre un paño junto a la bacha')),
        ],
        'faqs': [('¿Se puede lavar un termo de acero inoxidable en el lavavajillas?',
                  'No, salvo que el fabricante lo indique expresamente. El calor del ciclo puede dañar el vacío de la doble pared y las juntas de la tapa: el termo deja de mantener la temperatura.'),
                 ('¿Cada cuánto hay que limpiar el termo por dentro?',
                  'Enjuague diario, lavado con detergente semanal y limpieza profunda con vinagre una vez por mes si lo usás todos los días para mate o café.'),
                 ('¿El sarro del termo hace mal a la salud?',
                  'El sarro es principalmente carbonato de calcio del agua: no es tóxico, pero da mal sabor y aloja bacterias si se acumula. Conviene sacarlo apenas aparece.')],
    },
    'como-organizar-el-placard': {
        'imagen': ('/assets/img/blog/como-organizar-el-placard.jpg', 'Placard organizado con perchas iguales, cajas de tela y doblado vertical en cajones'),
        'title': 'Cómo Organizar el Placard: método simple en 5 pasos | El Gadget',
        'h1': 'Cómo organizar el placard (y que se mantenga ordenado)',
        'meta': 'Método práctico para organizar el placard en 5 pasos: qué sacar, cómo agrupar, dónde van los zapatos y qué organizadores usar para que el orden dure.',
        'fecha': '2026-07-11',
        'intro': 'Organizar el placard no es tirar todo y doblar mejor: es armar un sistema que se mantenga solo. Este método de 5 pasos funciona en placards grandes y chicos, y al final te decimos qué accesorios ayudan de verdad (y cuáles son puro chiche).',
        'secciones': [
            ("Deslizá: el antes y el después", """<div style="position:relative;max-width:640px;margin:0 auto 10px;border-radius:12px;overflow:hidden"><img src="/assets/img/blog/placard-organizado-despues.jpg" alt="El mismo placard organizado después del método" width="1200" height="670" style="display:block;width:100%;height:auto"><img src="/assets/img/blog/placard-desordenado-antes.jpg" alt="Placard desordenado antes de aplicar el método" width="1200" height="670" style="position:absolute;inset:0;width:100%;height:auto;clip-path:inset(0 50% 0 0)"><span style="position:absolute;top:10px;left:10px;background:rgba(20,21,26,.78);color:#fff;font-size:11px;font-weight:700;padding:4px 10px;border-radius:12px;letter-spacing:1px">ANTES</span><span style="position:absolute;top:10px;right:10px;background:rgba(20,21,26,.78);color:#FFC700;font-size:11px;font-weight:700;padding:4px 10px;border-radius:12px;letter-spacing:1px">DESPUÉS</span><input type="range" min="0" max="100" value="50" aria-label="Comparar antes y después" oninput="this.parentElement.querySelectorAll('img')[1].style.clipPath='inset(0 '+(100-this.value)+'% 0 0)'" style="position:absolute;left:4%;right:4%;bottom:8px;width:92%;accent-color:#FFC700;cursor:ew-resize"></div>Deslizá para comparar: el mismo placard aplicando este método, sin comprar un mueble nuevo."""),
            ('Paso 1 y 2: vaciar y decidir',
             'Sacá todo — sí, todo — y armá tres pilas: uso, no uso pero guardo, y se va. Sé honesto: lo que no usaste en un año no lo vas a usar. El placard ordenado empieza con menos cosas, no con más ganchos.'),
            ('Paso 3: agrupar por frecuencia, no por tipo',
             'Lo de todos los días a la altura de los ojos; lo de temporada arriba; lo ocasional abajo. El error clásico es agrupar "todas las camperas juntas" aunque uses una sola: el orden útil sigue tu rutina, no la lógica del catálogo.'),
            ('Paso 4: los zapatos, el jefe final',
             'Los zapatos sueltos destruyen cualquier placard. Un <a href="/coleccion/organizadores/">zapatero abatible</a> los saca del piso y los esconde en el espesor de un cuadro — ideal para recibidores y espacios chicos. Si van dentro del placard, las cajoneras con ruedas aprovechan el piso muerto.',
             ('/assets/img/blog/organizar-zapatos-zapatero-recibidor.jpg', 'Zapatero vertical delgado en un recibidor pequeño y luminoso con espejo, zapatos organizados')),
            ('Paso 5: sistemas que se mantienen solos',
             'La regla de oro: cada cosa necesita UN lugar obvio. Los <a href="/coleccion/organizadores/">organizadores colgantes y plegables</a> crean esos lugares sin obras ni muebles nuevos. Si guardar algo cuesta más de 5 segundos, el sistema falló — simplificá.',
             ('prod', r'colgante de puerta|organizador colgante')),
            ('Ordenar el placard por temporada',
             'El placard rinde el doble si solo contiene la temporada actual. Lo de invierno en verano (y viceversa) va arriba o abajo, en cajas o en un <a href="/coleccion/organizadores/">organizador plegable</a> rotulado. Dos rotaciones al año — abril y octubre — y de paso repasás el paso 2: lo que no usaste en toda la temporada, se va.',
             ('/assets/img/blog/ordenar-placard-por-temporada-cajas.jpg', 'Cajas organizadoras de tela con ropa de invierno en el estante superior del placard')),
            ('Closet pequeño: reglas de oro',
             'En un closet pequeño cada centímetro cuenta: perchas todas iguales (ocupan menos y se ve ordenado), doblado vertical en cajones para ver todo de frente, y la puerta como territorio útil con un colgante de puerta. La regla de entrada: si entra algo nuevo, sale algo viejo.'),
        ],
        'faqs': [('¿Cómo organizo un placard chico?',
                  'Verticalidad: colgantes de puerta, estantes divididos y cajoneras apilables. En placards chicos el aire entre estantes es el espacio más desperdiciado.'),
                 ('¿Cómo organizar los zapatos si no tengo lugar?',
                  'Zapatero vertical abatible: ocupa 20cm de profundidad contra la pared. Guarda pares de toda la familia en el espacio de un espejo de pie.')],
    },
    'como-organizar-una-cocina-pequena': {
        'imagen': ('/assets/img/blog/como-organizar-una-cocina-pequena.jpg', 'Cocina pequeña organizada con mesada despejada, organizadores colgantes y frascos alineados'),
        'title': 'Cómo Organizar una Cocina Pequeña: 7 trucos que liberan espacio | El Gadget',
        'h1': 'Cómo organizar una cocina pequeña sin obras',
        'meta': 'Trucos concretos para organizar una cocina pequeña: paredes, alturas, mesada libre y los organizadores que sí funcionan. Sin obras ni gastar de más.',
        'fecha': '2026-07-11',
        'intro': 'Una cocina pequeña no necesita más muebles: necesita usar mejor el espacio que ya tiene. Estos trucos van de lo gratis (reacomodar) a lo barato (organizadores puntuales), y todos apuntan a lo mismo: mesada libre y todo a mano.',
        'secciones': [
            ("Deslizá: el antes y el después", """<div style="position:relative;max-width:640px;margin:0 auto 10px;border-radius:12px;overflow:hidden"><img src="/assets/img/blog/cocina-pequena-organizada-despues.jpg" alt="La misma cocina pequeña con la mesada despejada y todo en su lugar" width="1200" height="670" style="display:block;width:100%;height:auto"><img src="/assets/img/blog/cocina-pequena-desordenada-antes.jpg" alt="Cocina pequeña con la mesada desbordada, antes de organizarla" width="1200" height="670" style="position:absolute;inset:0;width:100%;height:auto;clip-path:inset(0 50% 0 0)"><span style="position:absolute;top:10px;left:10px;background:rgba(20,21,26,.78);color:#fff;font-size:11px;font-weight:700;padding:4px 10px;border-radius:12px;letter-spacing:1px">ANTES</span><span style="position:absolute;top:10px;right:10px;background:rgba(20,21,26,.78);color:#FFC700;font-size:11px;font-weight:700;padding:4px 10px;border-radius:12px;letter-spacing:1px">DESPUÉS</span><input type="range" min="0" max="100" value="50" aria-label="Comparar antes y después" oninput="this.parentElement.querySelectorAll('img')[1].style.clipPath='inset(0 '+(100-this.value)+'% 0 0)'" style="position:absolute;left:4%;right:4%;bottom:8px;width:92%;accent-color:#FFC700;cursor:ew-resize"></div>Deslizá para comparar: la misma cocina, con la mesada liberada y las paredes trabajando."""),
            ('La mesada es sagrada',
             'La regla número uno: la mesada es para cocinar, no para guardar. Todo lo que vive sobre la mesada tiene que ganarse el lugar. El <a href="/categoria/bazar-y-cocina/">escurridor adhesivo extraíble</a> es el ejemplo perfecto: existe cuando lo necesitás, desaparece cuando no.',
             ('prod', r'escurridor.*adhesivo|organizador escurridor')),
            ('Usá las paredes y las alturas',
             'El espacio vertical es el gran desperdiciado: <a href="/coleccion/organizadores/">organizadores colgantes</a> para tazas y utensilios, estantes sobre la bacha y ganchos bajo las alacenas. Una pared bien usada equivale a una alacena entera.',
             ('/assets/img/blog/organizador-colgante-cocina-pared.jpg', 'Organizadores colgantes de metal negro con tazas y utensilios en la pared de una cocina')),
            ('Secado inteligente',
             'Si el secaplatos clásico te come media mesada, el <a href="/categoria/bazar-y-cocina/">rack de 3 niveles regulable</a> seca la vajilla de toda la familia en la huella de un plato. Altura en vez de superficie: la lógica de toda cocina chica.',
             ('/assets/img/blog/escurridor-platos-vertical-cocina-chica.jpg', 'Escurridor de platos vertical de varios niveles junto a la bacha de una cocina pequeña')),
            ('El cajón de "todo lo demás"',
             'Toda cocina tiene un cajón caótico. Está bien — pero que sea UNO, con divisores. Cuando el caos tiene borde, no se expande.'),
            ('Las alacenas, por dentro',
             'Una alacena mal usada es 40% aire: los apilables duplican los estantes, lo pesado va abajo y lo liviano arriba, y los frascos etiquetados de frente evitan el "compré de nuevo lo que ya tenía". Regla simple: si tenés que sacar tres cosas para llegar a una, falta un organizador o sobra una cosa.',
             ('prod', r'esquinero')),
            ('Errores que achican cualquier cocina',
             'Los tres clásicos: electrodomésticos que se usan una vez al mes viviendo sobre la mesada (van adentro, salen cuando trabajan), la bolsa de bolsas sin límite (un contenedor, lo que no entra se recicla) y los tuppers sin tapa (inventario cada tres meses, sin piedad). Corregí esos tres y la cocina "crece" sin mover una pared.'),
        ],
        'faqs': [('¿Qué es lo primero para ordenar una cocina chica?',
                  'Despejar la mesada. Sacá todo lo que no uses a diario y buscale lugar en altura o pared. El cambio visual es inmediato y motiva el resto.'),
                 ('¿Los organizadores adhesivos aguantan el peso?',
                  'Los de calidad sí, sobre azulejo o superficie lisa y limpia. Cada ficha de producto indica el peso máximo recomendado.')],
    },
    'ideas-para-decorar-una-habitacion': {
        'imagen': ('/assets/img/blog/ideas-para-decorar-una-habitacion.jpg', 'Dormitorio decorado con poco presupuesto: textiles en capas, velador de luz cálida y espejo grande contra la pared'),
        'title': 'Ideas para Decorar una Habitación: 8 cambios de bajo costo | El Gadget',
        'h1': 'Ideas para decorar una habitación sin gastar de más',
        'meta': 'Ideas reales para decorar una habitación: luz cálida, espejos, textiles y detalles con personalidad. Cambios de bajo costo y alto impacto, sin obras.',
        'fecha': '2026-07-11',
        'intro': 'Decorar una habitación no arranca por comprar muebles: arranca por la luz. Después vienen los espejos, los textiles y los detalles. Estas ideas están ordenadas por impacto — las primeras transforman más por menos plata.',
        'secciones': [
            ('1. Cambiá la luz, cambia todo',
             'La luz blanca de techo mata cualquier ambiente. Un <a href="/coleccion/lamparas-y-luces-led/">velador LED cálido</a> en la mesa de luz y alguna luz indirecta crean clima al instante. Los veladores con efecto infinito espejado suman deco de día y magia de noche — por eso son los favoritos en habitaciones juveniles.',
             ('prod', r'efecto infinito')),
            ('2. Espejos: el truco de los decoradores',
             'Un <a href="/categoria/deco/">espejo decorativo</a> bien ubicado duplica la luz natural y agranda visualmente el cuarto. Frente a la ventana si querés luz; frente a la puerta, amplitud.'),
            ('3. Detalles con personalidad',
             'Una lámpara con forma divertida, un objeto de <a href="/categoria/deco/">deco</a> que te represente. La habitación genérica se vuelve tuya con dos o tres piezas elegidas, no con veinte.'),
            ('4. El orden ES deco',
             'La habitación más linda se arruina con ropa en la silla. Un <a href="/coleccion/organizadores/">organizador</a> para eso que nunca tiene lugar (el zapatero, la cajonera) es la mejora estética más subestimada.'),
            ('5. Ideas para las paredes del dormitorio',
             'La pared de la cabecera es el punto focal natural del cuarto: un espejo decorativo o una composición simple alcanzan para vestirla. En las otras paredes, menos es más — una <a href="/coleccion/lamparas-y-luces-led/">guirnalda de luz cálida</a> enmarcando una ventana da más ambiente que diez cuadros chicos peleándose la atención.',
             ('/assets/img/blog/decorar-habitacion-guirnalda-luces-led.jpg', 'Guirnalda de luces LED cálidas enmarcando la ventana de una habitación juvenil de noche')),
            ('6. Habitación infantil o juvenil: color y luz',
             'En una habitación para niñas o niños, la fórmula es color + luz con personalidad: un <a href="/coleccion/lamparas-y-luces-led/">velador con forma</a> (unicornio, flamenco, dinosaurio) que funcione como luz de compañía, y deco que puedan elegir ellos — el cuarto que sienten propio se mantiene más ordenado, comprobado por cualquier madre o padre.',
             ('/assets/img/blog/decoracion-habitacion-infantil-velador.jpg', 'Velador LED con forma de unicornio encendido en una habitación infantil serena de noche')),
        ],
        'faqs': [('¿Cómo decorar una habitación con poco presupuesto?',
                  'Prioridad: luz cálida (velador LED), un espejo y orden. Con esas tres cosas la habitación cambia más que con un mueble nuevo, y gastás una fracción.'),
                 ('¿Qué luz conviene para una habitación juvenil?',
                  'LED cálida e indirecta: veladores con diseño (efecto infinito, formas) que sumen personalidad. Evitá la luz fría de techo como única fuente.')],
    },
    'como-sacar-pelos-de-mascota-de-la-ropa': {
        'imagen': ('/assets/img/blog/como-sacar-pelos-de-perro-del-sillon.jpg', 'Perro golden retriever descansando sobre una manta clara en un sillón gris con pelos visibles'),
        'title': 'Cómo Sacar Pelos de Perro y Gato de la Ropa: 6 métodos que funcionan | El Gadget',
        'h1': 'Cómo sacar los pelos de tu mascota de la ropa (y del sillón)',
        'meta': 'Métodos probados para sacar pelos de perro y gato de la ropa, el sillón y el auto: del guante de silicona al truco del lavarropas. Y cómo prevenir.',
        'fecha': '2026-07-11',
        'intro': 'Si tenés perro o gato, los pelos son parte del outfit. Pero hay diferencia entre convivir con algunos pelos y salir de casa hecho un pulóver de angora. Estos métodos funcionan, ordenados del más rápido al más profundo — y al final, el secreto real: la prevención.',
        'secciones': [
            ('El método más rápido: guante de silicona',
             'El <a href="/categoria/accesorios-para-mascotas/">guante removedor de pelos</a> junta con una pasada lo que el rodillo de cinta tarda media hora: los pelos se adhieren a la silicona por estática y se enjuaga bajo la canilla. Sirve para ropa, sillón, manta del auto — y para cepillar directamente a tu mascota.',
             ('/assets/img/blog/guante-quita-pelos-perro-gato.jpg', 'Guante de silicona para quitar pelos de mascota cubierto de pelo de perro sobre un sillón gris')),
            ('Trucos caseros que suman',
             'Goma de látex o guante de cocina húmedo en pasadas cortas; secarropas 10 minutos con una toalla seca antes de lavar (afloja el pelo); y al lavar, media taza de vinagre blanco en el enjuague relaja las fibras y suelta el pelo pegado.'),
            ('La prevención es el 80%',
             'El pelo que no llega a la ropa no hay que sacarlo: cepillá a tu perro o gato 2-3 veces por semana con un <a href="/categoria/accesorios-para-mascotas/">cepillo o guante para el pelo</a> — en época de muda, a diario. Menos pelo suelto en el animal = menos en tu sillón.',
             ('prod', r'guante para peinar|cepillo.*mascota|guante removedor')),
            ('Bonus: la zona del comedero',
             'Donde come tu mascota se junta pelo, agua y comida. Una <a href="/categoria/accesorios-para-mascotas/">alfombra para el comedero</a> contiene el desastre en un rectángulo lavable — un truco chico que ahorra limpieza diaria.'),
            ('El protocolo del lavarropas',
             'Para que el lavarropas no redistribuya el pelo entre TODA la ropa: sacudí o pasá el guante antes de meter las prendas, lavá lo de la mascota (mantas, fundas) separado del resto, y limpiá el filtro después de cada lavado peludo. El vinagre blanco en el enjuague ayuda a que las fibras suelten lo que quedó.'),
            ('Pelos en el auto: la solución de dos minutos',
             'El tapizado del auto es velcro para el pelo de perro. El combo que funciona: manta o funda lavable en el asiento donde viaja (se sacude afuera y listo), y <a href="/categoria/accesorios-para-mascotas/">guante de silicona</a> ligeramente húmedo para las pasadas de mantenimiento en tapizados y alfombras. Dos minutos antes de devolver el auto prestado.',
             ('/assets/img/blog/quitar-pelos-de-perro-del-auto.jpg', 'Perro sentado sobre una manta protectora gris en el asiento trasero de un auto')),
        ],
        'faqs': [('¿Cómo saco los pelos de gato del sillón?',
                  'Guante de silicona ligeramente húmedo en pasadas firmes hacia un mismo lado: el pelo se junta en rollitos que levantás de una. Para tapizados delicados, aspiradora con cepillo suave antes.'),
                 ('¿Por qué mi perro larga tanto pelo?',
                  'La muda estacional (otoño y primavera) es normal. Si es excesiva fuera de temporada, consultá al veterinario: puede ser alimentación o piel. El cepillado frecuente regula la muda normal.')],
    },
}
