# -*- coding: utf-8 -*-
"""Posts del blog — contenido informacional que alimenta a las categorías.

Keywords del research SEO-KEYWORDS/blog-*.csv (asignaciones en
MAPA-KEYWORDS.md: una primaria = una URL). Regla: el blog responde
preguntas y linkea al catálogo; NUNCA apunta a las keywords comerciales
de categorías/colecciones (eso sería canibalización).
Los cuerpos admiten HTML (links internos al catálogo).
"""

BLOG_POSTS = {
    'mewing': {
        'imagen': ('/assets/img/blog/mewing-que-es-jawline.jpg', 'Persona joven tocándose la mandíbula mientras mira el celular, dudando si el mewing funciona'),
        'title': 'Mewing: qué es, cómo se hace y si realmente funciona (2026) | El Gadget',
        'h1': 'Mewing: qué es, cómo se hace y si de verdad funciona',
        'meta': '¿El mewing funciona? Qué dice la ciencia sobre esta técnica de postura de lengua para la mandíbula, cómo se hace paso a paso y qué la define de verdad.',
        'fecha': '2026-07-14',
        'intro': 'El mewing es una de las tendencias de estética facial más virales de TikTok: la idea de que apoyar la lengua contra el paladar, de forma constante, afina y marca la mandíbula. Suena simple y gratis, así que la pregunta que todos se hacen es la correcta: <strong>¿el mewing realmente funciona o es otra moda de internet?</strong> Acá va la respuesta honesta —con lo que dice la ciencia, cómo se hace bien y qué es lo que de verdad define una mandíbula—.',
        'secciones': [
            ('¿Qué es el mewing?',
             'El término "mewing" viene del apellido de los ortodoncistas británicos John y Mike Mew, que popularizaron la idea de la <strong>postura oral correcta</strong>. Mewing es, en concreto, mantener <strong>toda la lengua apoyada contra el paladar</strong> (el techo de la boca) en reposo —no solo la punta—, con los labios cerrados, los dientes apenas en contacto y respirando por la nariz. La teoría dice que esa postura sostenida, con los años, guía el desarrollo de la cara y marca más la línea mandibular. Es una técnica, no un aparato ni una cirugía: hacerla no cuesta nada.'),
            ('Cómo se hace el mewing, paso a paso',
             'Si querés probarlo, la técnica correcta es esta: <strong>1)</strong> Cerrá los labios y respirá por la nariz. <strong>2)</strong> Llevá <strong>toda</strong> la lengua contra el paladar, incluida la parte de atrás, no solo la punta. Un truco para encontrar la posición: decí "ng" (como en "tango") y sentí dónde queda la lengua. <strong>3)</strong> Los dientes de arriba y abajo apenas se tocan, sin apretar. <strong>4)</strong> Sostené esa postura como estado de reposo, todo el día, hasta que se vuelva automática. No hay que hacer fuerza ni "empujar": es una postura, no un ejercicio de potencia. Y ojo con eso último, porque forzar es justo por donde aparecen los problemas.',
             ('/assets/img/blog/mewing-postura-lengua-paladar.jpg', 'Ilustración del corte lateral de la boca con la lengua apoyada contra el paladar, la postura correcta del mewing')),
            ('¿El mewing realmente funciona? La evidencia honesta',
             'Acá va la parte que la mayoría de los videos se saltea. <strong>No existe ningún estudio científico revisado por pares que demuestre que el mewing cambie la estructura ósea de la cara en un adulto.</strong> La <a href="https://aaoinfo.org/whats-trending/is-mewing-bad-for-you/" target="_blank" rel="noopener">Asociación Americana de Ortodoncistas (AAO)</a> lo dice de forma directa: no hay investigación que respalde que el mewing altere la estructura facial. Lo que circula como "prueba" son testimonios y fotos de antes y después —muchas veces con mejor luz, ángulo y postura—, no ensayos clínicos. Lo que sí reconocen varios profesionales es un beneficio real pero más modesto: <strong>tomar conciencia de la postura de la lengua y de respirar por la nariz</strong>, algo que hace bien más allá de la estética.'),
            ('Adultos vs. adolescentes: por qué la edad cambia todo',
             '¿Por qué tanta cautela con los adultos? Porque los huesos de la cara <strong>terminan de crecer en la pubertad</strong>. Antes de esa edad, la postura oral puede influir en cómo se desarrolla la mandíbula (por eso la ortodoncia trabaja tanto en la infancia). Después, el hueso ya está formado: mantener la lengua arriba no lo va a remodelar. De hecho, <strong>hasta los propios hermanos Mew admiten que el mewing no debería funcionar en un adulto</strong>. Si tenés más de 18, tomá el mewing como un hábito de postura, no como una promesa de cambiar tu cara.'),
            ('Qué SÍ marca una mandíbula definida',
             'Si el mewing no es la solución mágica, ¿qué marca de verdad una mandíbula? Tres cosas, en orden de impacto: <strong>1) El porcentaje de grasa corporal.</strong> La línea mandibular se "esconde" bajo la grasa del rostro y el cuello; bajar la grasa general es, de lejos, lo que más la revela. <strong>2) La genética.</strong> La forma de base del hueso la heredás, y eso pone el techo de lo que se puede lograr. <strong>3) La postura.</strong> Cabeza erguida y hombros atrás estilizan el cuello al instante (más sobre esto en la <a href="/blog/como-reducir-la-papada/">guía de la papada</a>). Ninguna de las tres es un truco de 30 segundos, pero son las que mueven la aguja de verdad.',
             ('/assets/img/blog/que-define-la-mandibula-grasa-corporal.jpg', 'Persona corriendo al aire libre: bajar el porcentaje de grasa corporal es lo que más marca la mandíbula')),
            ('¿Y los ejercitadores de mandíbula?',
             'Acá aparece algo que se confunde seguido con el mewing: los <strong>ejercitadores de mandíbula</strong>, esas piezas de silicona que se muerden. No son mewing —el mewing es postura de lengua, sin aparato—. Un ejercitador trabaja por resistencia el <strong>músculo masetero</strong>, el que usás para masticar, igual que una mancuerna trabaja el bíceps. Con uso <strong>moderado</strong> puede tonificar y fortalecer ese músculo. Lo que NO hace, y conviene tenerlo claro: <strong>no elimina grasa ni papada</strong> (la grasa no se reduce de forma localizada) y <strong>no reestructura el hueso</strong>. De hecho, <a href="https://www.medicalnewstoday.com/articles/jawzrsize-review" target="_blank" rel="noopener">las revisiones médicas sobre estos aparatos</a> encontraron poca o nula evidencia de cambios estéticos. Y una advertencia importante: usarlos en exceso puede <strong>sobrecargar la articulación de la mandíbula (ATM)</strong> y causar dolor. Si querés entrenar el masetero como parte de tu rutina —sabiendo todo esto—, hacelo en sesiones cortas y sin forzar.',
             ('prod', r'ejercitador de mand[íi]bula')),
            ('Errores y riesgos que conviene evitar',
             'Para cerrar, los errores más comunes: <strong>forzar la lengua o apretar los dientes</strong> (el mewing es suave; apretar lleva a bruxismo y dolor de ATM), <strong>esperar cambios óseos siendo adulto</strong> (no van a pasar) e <strong>ignorar un problema de respiración</strong> —si respirás por la boca por congestión o apnea, eso merece un profesional, no un truco de TikTok—. Y si lo que en realidad te molesta es la <a href="/blog/como-reducir-la-papada/">papada o el doble mentón</a>, tenemos una guía aparte con lo que funciona de verdad. La conclusión honesta sobre el mewing: como recordatorio de buena postura de lengua y respiración nasal, está perfecto; como método para transformar la cara de un adulto, la ciencia no lo respalda.'),
        ],
        'faqs': [('¿El mewing funciona en adultos?',
                  'No hay evidencia científica de que el mewing cambie la estructura ósea de la cara en adultos: los huesos terminan de crecer en la pubertad. Sirve como hábito de postura de lengua y respiración nasal, no como método para remodelar la mandíbula.'),
                 ('¿Cuánto tarda en hacer efecto el mewing?',
                  'Los defensores hablan de meses o años, pero no hay estudios que confirmen un resultado estético medible en adultos. Si buscás marcar la mandíbula, bajar el porcentaje de grasa corporal da resultados mucho más comprobables.'),
                 ('¿El mewing es seguro?',
                  'Hecho de forma suave —solo apoyar la lengua, sin apretar los dientes— es inofensivo. El riesgo aparece al forzar, o al confundirlo con morder aparatos de resistencia, que usados en exceso pueden causar dolor de mandíbula (ATM).')],
    },
    'como-reducir-la-papada': {
        'imagen': ('/assets/img/blog/como-reducir-la-papada-doble-menton.jpg', 'Persona haciendo un ejercicio suave de postura de cuello y mentón para reducir la papada'),
        'title': 'Cómo reducir la papada: qué funciona de verdad (2026) | El Gadget',
        'h1': 'Cómo reducir la papada: qué funciona de verdad (y qué no)',
        'meta': 'Qué es la papada, por qué aparece y qué funciona de verdad para reducirla: ejercicios, postura, hábitos y tratamientos médicos comparados con honestidad.',
        'fecha': '2026-07-14',
        'intro': 'La papada —o doble mentón— es una de esas cosas que aparecen en cada foto de grupo y en cada videollamada, y que cuesta disimular. Internet está lleno de soluciones mágicas: ejercicios de 5 minutos, cremas, aparatos. Antes de gastar plata o tiempo, conviene entender <strong>qué es la papada, por qué aparece y qué funciona de verdad para reducirla</strong>. Adelanto: hay cosas que ayudan y cosas que son puro humo. Vamos con la versión honesta.',
        'secciones': [
            ('¿Por qué aparece la papada?',
             'La papada es, en la mayoría de los casos, <strong>acumulación de grasa en la zona submentoniana</strong> (debajo del mentón). Aparece por varios motivos que suelen combinarse: <strong>el porcentaje de grasa corporal</strong> (a más grasa general, más probable), <strong>la genética</strong> (hay familias con tendencia, sin importar el peso), <strong>la edad</strong> (con los años la piel pierde firmeza y el cuello se afloja) y <strong>la postura</strong> (pasar horas mirando el celular hacia abajo acentúa el pliegue). Entender la causa importa, porque la solución cambia según de dónde venga: no es lo mismo grasa que flacidez de piel.'),
            ('El mito de la reducción localizada',
             'El mito más caro de todos: <strong>no se puede "quemar" grasa de una zona específica del cuerpo ejercitando esa zona.</strong> Ni la papada, ni la panza, ni los brazos. La reducción localizada de grasa no existe: cuando bajás grasa, el cuerpo decide de dónde la saca —y en gran parte lo decide tu genética—. Por eso ningún ejercicio de cuello, por más que lo hagas todos los días, va a "derretir" la grasa de la papada de forma directa. Tenerlo claro te ahorra plata en aparatos que prometen justamente eso.'),
            ('Ejercicios para la papada: qué esperar de verdad',
             '¿Entonces los ejercicios no sirven? Sirven, pero para algo más modesto de lo que prometen: <strong>tonifican los músculos del cuello y la mandíbula</strong> (el platisma, entre otros), lo que puede mejorar levemente la firmeza y la definición de la zona. No eliminan la grasa, pero como parte de una rutina acompañan. Tres ejemplos suaves: <strong>1)</strong> "Chin tuck": llevá el mentón hacia atrás, haciendo "papada" a propósito, sin bajar la cabeza; sostené 5 segundos y repetí. <strong>2)</strong> Mirando al techo, apoyá la lengua en el paladar y sostené. <strong>3)</strong> Girá la cabeza a un lado y estirá el cuello. Hacelos con suavidad: forzar el cuello o la mandíbula no acelera nada y puede lastimar.'),
            ('La postura importa: el "text neck"',
             'Uno de los factores más subestimados es la <strong>postura</strong>. Pasar horas con la cabeza inclinada hacia el celular —lo que se conoce como "text neck" o cuello de texto— acorta y afloja los músculos del frente del cuello, y acentúa visualmente la papada. La buena noticia es que esto sí lo controlás: subí el celular a la altura de los ojos, mantené la <strong>cabeza erguida y los hombros hacia atrás</strong>, y hacé pausas si trabajás muchas horas frente a una pantalla. Corregir la postura no elimina la grasa, pero mejora al instante cómo se ve el cuello —y de paso te cuida la cervical—.',
             ('/assets/img/blog/postura-cuello-papada-celular.jpg', 'Persona de perfil encorvada mirando el celular con postura de text neck, que acentúa la papada')),
            ('Tratamientos médicos: Belkyra, ácido desoxicólico y cirugía',
             'Si la papada es de grasa y te molesta mucho, los tratamientos que <strong>sí</strong> reducen grasa son médicos —y por eso cuestan y tienen contraindicaciones—. Los más conocidos: las <strong>inyecciones de ácido desoxicólico</strong> (la marca más nombrada es Belkyra/Kybella), que disuelven la grasa submentoniana en varias sesiones; la <strong>criolipólisis</strong> (que "congela" la grasa); y la <strong>liposucción o cirugía del cuello</strong> para los casos más marcados o con mucha flacidez. Los precios varían muchísimo según la zona y el profesional, y casi siempre hacen falta varias sesiones, así que pedí presupuesto y consultá con un médico matriculado. La regla honesta: <strong>estos son los únicos métodos con evidencia de que reducen la grasa de la papada</strong>; todo lo demás (ejercicios, postura, aparatos) acompaña, no reemplaza.'),
            ('¿Y los ejercitadores de mandíbula?',
             'Como los ejercitadores de mandíbula se venden muchas veces con la promesa de "eliminar la papada", aclaremos: <strong>no lo hacen</strong>. Trabajan el músculo masetero (el de masticar) por resistencia, que <strong>no tiene relación con la grasa submentoniana</strong>. Un <a href="https://www.ncbi.nlm.nih.gov/pmc/articles/PMC11681191/" target="_blank" rel="noopener">estudio de caso publicado</a> siguió a dos personas usando uno de estos aparatos durante unos tres meses: <strong>ninguna reportó cambios notables</strong>. Y hay que sumar el riesgo: <a href="https://www.docseducation.com/blog/dangers-jawzrsize-and-jaw-exercise-equipment" target="_blank" rel="noopener">los odontólogos advierten</a> que el uso excesivo puede causar problemas en la articulación (ATM) y desplazamiento dental. ¿Sirven para algo? Para <strong>entrenar el músculo de la mandíbula</strong> si eso es lo que buscás, con moderación y expectativas realistas. Para la papada de grasa, no.',
             ('prod', r'ejercitador de mand[íi]bula')),
            ('Lo que de verdad mueve la aguja: composición corporal',
             'Resumiendo, sin vueltas: lo que de verdad reduce la papada de grasa es <strong>bajar el porcentaje de grasa corporal general</strong> —alimentación y actividad física sostenidas—, acompañado de buena postura y, si querés y podés, un tratamiento médico para los casos marcados. Los ejercicios y aparatos tonifican y acompañan, pero no hacen magia. Si estás encarando la parte de composición corporal, en <a href="/categoria/fitness/">accesorios de fitness</a> tenés elementos para entrenar en casa; y si llegaste hasta acá por la moda del jawline, mirá también nuestra guía honesta sobre <a href="/blog/mewing/">qué es el mewing y si funciona</a>. Menos humo y más constancia: es lo que termina funcionando.'),
        ],
        'faqs': [('¿Los ejercicios eliminan la papada?',
                  'No de forma directa: tonifican los músculos del cuello y la mandíbula, pero no queman la grasa submentoniana (la reducción localizada de grasa no existe). Ayudan como complemento de una baja de grasa corporal general.'),
                 ('¿Se puede reducir la papada sin cirugía?',
                  'Sí, en muchos casos: bajando el porcentaje de grasa corporal general, mejorando la postura y, si hace falta, con tratamientos médicos no quirúrgicos como las inyecciones de ácido desoxicólico. La cirugía se reserva para casos marcados o con mucha flacidez.'),
                 ('¿Por qué tengo papada si no soy gordo/a?',
                  'Por genética o por postura. Hay personas delgadas con tendencia genética a acumular grasa en esa zona, y la postura de cabeza hacia el celular acentúa el pliegue aunque tu peso sea normal.')],
    },
    'como-mejorar-la-postura': {
        'imagen': ('/assets/img/blog/como-mejorar-la-postura.jpg', 'Persona sentada con la espalda erguida y buena postura frente a un escritorio'),
        'title': 'Cómo mejorar la postura: ejercicios, hábitos y qué funciona (2026) | El Gadget',
        'h1': 'Cómo mejorar la postura: qué funciona de verdad',
        'meta': 'Cómo mejorar y corregir la postura: por qué se arruina, ejercicios para enderezar la espalda, ergonomía, cómo quitar la joroba del cuello y si sirven los correctores.',
        'fecha': '2026-07-14',
        'intro': 'Pararse derecho, llevar los hombros hacia atrás y verse (y sentirse) mejor: mejorar la postura es una de las tendencias de autocuidado que más creció —del dolor de espalda del que labura sentado al "posturemaxxing" de TikTok—. La buena noticia es que la postura <strong>se puede mejorar de verdad</strong>. La mala: no es con un truco ni con un aparato mágico. Acá va la guía honesta —lo que funciona según la evidencia, ejercicios concretos y qué esperar de un corrector—.',
        'secciones': [
            ('¿Por qué se arruina la postura?',
             'Casi todas las malas posturas modernas tienen el mismo origen: <strong>pasamos horas en la misma posición</strong>, casi siempre encorvados hacia una pantalla. Sentados frente a la compu con los hombros redondeados, o con la cabeza inclinada hacia el celular (el famoso "tech neck" o cuello de texto), algunos músculos se acortan y otros se debilitan. Con el tiempo esa posición se vuelve tu estado por defecto: el cuerpo aprende a encorvarse. No es un problema de huesos torcidos, sino de <strong>hábito y equilibrio muscular</strong> —y eso, justamente, es lo que se puede reentrenar—.'),
            ('Cómo corregir la postura: por dónde empezar',
             'Antes de comprar nada, entendé el principio: <strong>la postura se corrige fortaleciendo los músculos que la sostienen, mejorando la ergonomía y moviéndote más seguido</strong>. No hay atajo. Un cuerpo que pasa 8 horas quieto y encorvado no se endereza solo por ponerse algo encima; se endereza cuando los músculos de la espalda alta, el cuello y el core se vuelven lo bastante fuertes como para sostenerte sin esfuerzo consciente. Los tres pilares, en orden: <strong>1)</strong> ejercicio de fuerza y movilidad, <strong>2)</strong> ergonomía del puesto de trabajo, <strong>3)</strong> pausas para cambiar de posición. Todo lo demás —incluidos los correctores— es un apoyo, no un reemplazo.'),
            ('Ejercicios para mejorar la postura',
             'Los ejercicios son lo que más mueve la aguja, y no necesitás gimnasio. Cuatro que apuntan justo a los músculos que se debilitan al estar sentado: <strong>1) Retracción de mentón (chin tuck):</strong> llevá el mentón hacia atrás como haciendo "papada", sostené 5 segundos, 10 repeticiones — combate la cabeza adelantada. <strong>2) Apertura de pecho:</strong> entrelazá las manos detrás de la espalda y llevá los hombros hacia atrás y abajo. <strong>3) "Band pull-apart":</strong> con una banda elástica, tirá de los codos hacia atrás juntando los omóplatos — fortalece la espalda alta. <strong>4) Plancha:</strong> activa el core, base de toda postura. Hacelos a diario y con suavidad: la constancia le gana a la intensidad.',
             ('/assets/img/blog/ejercicios-para-mejorar-la-postura.jpg', 'Persona haciendo un ejercicio de apertura de pecho y hombros sobre una colchoneta para mejorar la postura')),
            ('Ergonomía: acomodá tu puesto de trabajo',
             'Podés hacer todos los ejercicios del mundo, pero si volvés a encorvarte 8 horas por día, remás contra la corriente. Acomodá tu espacio: <strong>la pantalla a la altura de los ojos</strong> (subí la notebook con un soporte o unos libros y usá teclado aparte), <strong>los pies apoyados en el piso</strong>, la <strong>espalda contra el respaldo</strong> y los antebrazos paralelos al escritorio. Una <a href="/categoria/home/">silla con buen respaldo</a> y una <a href="/coleccion/lamparas-y-luces-led/">buena iluminación</a> ayudan a no encorvarte para ver. Y lo más importante (y más barato): <strong>levantate cada 30-45 minutos</strong>. La mejor postura es la próxima; ninguna es buena si la mantenés durante horas.',
             ('/assets/img/blog/ergonomia-puesto-de-trabajo-postura.jpg', 'Puesto de trabajo ergonómico con la laptop elevada a la altura de los ojos y la espalda alineada')),
            ('Cómo quitar la joroba del cuello (tech neck)',
             'La "joroba" en la base del cuello (a veces llamada joroba de viuda o tech neck) suele ser la suma de dos cosas: <strong>la cabeza adelantada</strong> por mirar el celular hacia abajo y, a veces, algo de grasa en la zona. Para mejorarla, la receta es la misma de arriba —chin tucks, fortalecer la espalda alta, subir el celular a la altura de los ojos— más paciencia: es un hábito de años que se revierte de a poco. Y si además te preocupa la papada o la línea de la mandíbula, tenemos guías honestas sobre <a href="/blog/como-reducir-la-papada/">cómo reducir la papada</a> y <a href="/blog/mewing/">qué es el mewing y si funciona</a> — la postura es de las pocas cosas que ayudan a las tres.',
             ('/assets/img/blog/postura-cuello-papada-celular.jpg', 'Persona encorvada mirando el celular con la cabeza adelantada, la postura que genera la joroba del cuello o tech neck')),
            ('¿Sirven los correctores de postura? La verdad',
             'La pregunta del millón, con respuesta honesta. Los correctores de postura <strong>funcionan como recordatorio y soporte mientras los usás</strong>: te llevan los hombros hacia atrás y te "avisan" cuando te encorvás. La <a href="https://www.medicalnewstoday.com/articles/do-posture-correctors-work" target="_blank" rel="noopener">evidencia disponible</a> sugiere que pueden ayudar en el <strong>corto plazo</strong> a reducir los hombros redondeados y la cabeza adelantada, pero <strong>solo combinados con ejercicio</strong>. Lo que NO hacen: corregir la postura de forma permanente por sí solos. Peor aún, los <a href="https://www.physiotherapymatters.co.uk/blog/back-posture-braces-do-they-work-physiotherapy-matters/" target="_blank" rel="noopener">fisioterapeutas advierten</a> que apoyarte demasiado en un corrector puede <strong>debilitar los músculos posturales</strong> (si el aparato hace el trabajo, el músculo se relaja). La forma correcta de usarlo: como <strong>muleta temporal</strong> para tomar conciencia mientras fortalecés, unos ratos por día — no todo el día ni para siempre.',
             ('prod', r'corrector.*postura')),
            ('Cuándo consultar a un profesional',
             'La postura "de hábito" se mejora en casa. Pero hay señales para ver a un médico o kinesiólogo en vez de arreglarlo por tu cuenta: <strong>dolor de espalda persistente o que se irradia</strong>, hormigueos, una curvatura marcada que apareció rápido, o dolor que no cede con el descanso. En chicos y adolescentes, una curvatura lateral de la columna (escoliosis) sí tiene tratamiento específico con evidencia. Para todo lo demás —el clásico "me la paso encorvado frente a la compu"—, la fórmula es la de esta guía: movete, fortalecé, acomodá tu espacio y usá el corrector como ayuda, no como solución.'),
        ],
        'faqs': [('¿Cuánto tarda en mejorar la postura?',
                  'Depende de cuánto tiempo la hayas mantenido mal, pero con ejercicios diarios y buena ergonomía se notan cambios en algunas semanas. Es un hábito que se reentrena de a poco: la constancia importa más que la intensidad.'),
                 ('¿Los correctores de postura sirven?',
                  'Como recordatorio y soporte a corto plazo, combinados con ejercicio, pueden ayudar. Pero no corrigen la postura de forma permanente por sí solos, y usarlos todo el día puede debilitar los músculos. Usalos como ayuda temporal mientras fortalecés.'),
                 ('¿Cómo quito la joroba del cuello?',
                  'Con retracciones de mentón (chin tucks), fortaleciendo la espalda alta y subiendo el celular a la altura de los ojos para dejar de mirar hacia abajo. Es gradual: se revierte con hábito sostenido, no de un día para el otro.')],
    },
    'como-dejar-de-roncar': {
        'imagen': ('/assets/img/blog/como-dejar-de-roncar-dormir-mejor.jpg', 'Persona durmiendo plácidamente en un dormitorio cálido y tranquilo'),
        'title': 'Cómo dejar de roncar y dormir mejor: qué funciona (2026) | El Gadget',
        'h1': 'Cómo dejar de roncar (y dormir mejor)',
        'meta': 'Por qué roncás y qué funciona para dejar de roncar: dilatadores nasales, posición, hábitos, cuándo el ronquido es apnea, y las claves del sleepmaxxing para dormir mejor.',
        'fecha': '2026-07-14',
        'intro': 'Dormís 8 horas y te levantás igual de cansado. O tu pareja te avisa (otra vez) que roncás. El sueño se puso de moda —el "sleepmaxxing" es furor en TikTok— y con él, mil productos que prometen arreglarlo. Antes de gastar, entendé qué funciona de verdad para <strong>dejar de roncar y dormir mejor</strong>, qué es puro humo y cuándo el ronquido es una señal para ver a un médico. Guía honesta, sin cuentos.',
        'secciones': [
            ('¿Por qué roncás?',
             'El ronquido es un sonido: el aire que pasa por una vía respiratoria parcialmente obstruida hace vibrar los tejidos blandos de la garganta, el paladar o la nariz. Cualquier cosa que estreche ese paso o relaje de más esos tejidos te hace roncar más. Las causas más comunes: <strong>la nariz congestionada</strong> (resfrío, alergia, tabique desviado), <strong>dormir boca arriba</strong> (la lengua y el paladar caen hacia atrás), <strong>el alcohol o los sedantes antes de dormir</strong> (relajan de más la garganta), el <strong>sobrepeso</strong> (tejido extra alrededor del cuello) y la <strong>edad</strong>. Saber tu causa importa, porque la solución cambia: no es lo mismo un ronquido nasal que uno de garganta.'),
            ('Qué funciona para dejar de roncar',
             'Lo primero, y gratis: <strong>dormí de costado</strong> (el viejo truco de coser una pelota de tenis en la espalda del pijama funciona), <strong>evitá el alcohol</strong> las 3 horas previas a dormir y <strong>destapate la nariz</strong> si estás congestionado. Si tu ronquido es de <strong>origen nasal</strong>, ahí entran los <strong>dilatadores nasales</strong>: se colocan en las fosas para mantenerlas abiertas y mejorar el flujo de aire. La <a href="https://pmc.ncbi.nlm.nih.gov/articles/PMC5187471/" target="_blank" rel="noopener">evidencia</a> dice que ayudan de forma <strong>modesta y solo a algunas personas</strong> —las que roncan por la nariz—, no a todas ni para siempre. Son baratos, así que como primera prueba tienen sentido; solo no esperes magia.',
             ('prod', r'dilatadores nasales')),
            ('⚠️ Cuándo el ronquido es apnea del sueño',
             'Atención con esto, que es lo más importante de toda la guía. A veces el ronquido es la señal de una <strong>apnea del sueño</strong>: una condición en la que la respiración se corta repetidamente durante la noche. Las banderas rojas: <strong>ronquido muy fuerte</strong>, <strong>pausas en la respiración o ahogos</strong> (que suele notar quien duerme al lado), <strong>sueño no reparador</strong> con somnolencia durante el día y dolor de cabeza al despertar. Si te suena, ningún dilatador ni truco de TikTok alcanza: <strong>la apnea necesita evaluación médica</strong> (los dilatadores nasales, de hecho, no mejoran la apnea según los estudios). No es para asustarte: es para que no pierdas tiempo con parches si el problema es serio.'),
            ('Sleepmaxxing: qué sirve y qué es humo',
             'El "sleepmaxxing" es la moda de optimizar el sueño apilando hábitos y productos. La buena noticia: <strong>la base que de verdad funciona es aburrida y gratis</strong>, y la ciencia la recomienda hace décadas: <strong>horario constante</strong> para acostarte y levantarte, <strong>cuarto oscuro y fresco</strong>, <strong>nada de pantallas</strong> la última hora y <strong>nada de cafeína</strong> a la tarde-noche. Lo que el trend aporta es motivación para cumplirlas. Lo que <strong>conviene evitar</strong>: el <strong>mouth taping</strong> (taparse la boca con cinta para "obligarte" a respirar por la nariz) se volvió viral, pero <a href="https://www.webmd.com/sleep-disorders/mouth-taping" target="_blank" rel="noopener">los expertos lo desaconsejan</a> —no tiene evidencia sólida y puede ser peligroso, sobre todo si tenés apnea o la nariz tapada—. En resumen: quedate con lo básico probado y desconfiá de los hacks extremos.',
             ('/assets/img/blog/entorno-para-dormir-mejor.jpg', 'Dormitorio oscuro, fresco y ordenado, el entorno ideal para dormir mejor según el sleepmaxxing')),
            ('Dormir con ruido: silenciá el entorno',
             'A veces no roncás vos: es el ruido de afuera (o de al lado) el que te arruina el sueño. Ahí, la solución simple y efectiva son los <strong>tapones anti-ruido</strong>: atenúan de forma pasiva el tránsito, los vecinos o el ronquido de tu pareja para que puedas descansar. Un dato honesto: los tapones de silicona o espuma <strong>reducen</strong> el ruido, no lo cancelan por completo como los auriculares electrónicos —pero para dormir suelen alcanzar de sobra, y son mucho más baratos—. Combinados con una <a href="/coleccion/lamparas-y-luces-led/">luz cálida y tenue</a> a la noche y una rutina sin pantallas, hacen mucho por tu descanso.',
             ('prod', r'tapones anti')),
            ('La fórmula honesta para dormir mejor',
             'Dormir mejor no es un solo producto: es <strong>ordenar los básicos</strong> (horario, oscuridad, frío, sin pantallas ni alcohol antes de dormir), <strong>atacar tu causa de ronquido</strong> (posición, nariz, peso) con la ayuda de un dilatador si es nasal, <strong>silenciar el entorno</strong> con tapones si hace falta, y <strong>consultar a un médico</strong> si sospechás apnea. Nada de magia, todo sentido común. Y si te gusta este tipo de bienestar sin humo, mirá también nuestras guías honestas sobre <a href="/blog/como-mejorar-la-postura/">cómo mejorar la postura</a> y <a href="/blog/mewing/">qué es el mewing y si funciona</a>.',
             ('/assets/img/blog/rutina-antes-de-dormir-sin-pantallas.jpg', 'Persona leyendo un libro antes de dormir con el celular apartado, una rutina sin pantallas para descansar mejor')),
        ],
        'faqs': [('¿Los dilatadores nasales funcionan para dejar de roncar?',
                  'Ayudan de forma modesta a las personas cuyo ronquido es de origen nasal (congestión, tabique, válvula estrecha), mejorando el paso del aire. No funcionan para todos ni para el ronquido de garganta, y no tratan la apnea del sueño.'),
                 ('¿Cómo sé si mi ronquido es apnea del sueño?',
                  'Las señales de alarma son ronquido muy fuerte con pausas en la respiración o ahogos, sueño no reparador, somnolencia de día y dolor de cabeza al despertar. Si te pasa, consultá con un médico: la apnea necesita evaluación profesional, no un dilatador.'),
                 ('¿El mouth taping (taparse la boca) sirve para dormir?',
                  'Se volvió viral pero los expertos lo desaconsejan: no tiene evidencia sólida y puede ser peligroso, sobre todo si tenés apnea no diagnosticada o congestión nasal. Mejor quedate con los hábitos de sueño probados.')],
    },
    'regalos-de-navidad': {
        'imagen': ('/assets/img/blog/regalos-de-navidad-argentina.jpg', 'Regalos de Navidad envueltos en papel kraft con cintas amarillas y ramas de pino junto a un arbolito con luces cálidas'),
        'title': 'Regalos de Navidad 2026: ideas por presupuesto y cuándo comprar | El Gadget',
        'h1': 'Regalos de Navidad 2026: ideas que llegan a tiempo',
        'meta': 'Ideas de regalos de Navidad 2026 por presupuesto y por destinatario, cuándo es Navidad y Reyes, y cómo comprar online con tiempo para que lleguen. Envío a todo el país.',
        'fecha': '2026-07-13',
        'intro': 'La Navidad llega siempre igual: de golpe. Este año es el <strong>viernes 25 de diciembre</strong>, y entre la cena, el arbolito y el amigo invisible de la oficina, la lista de regalos se hace larga. Acá te la simplificamos: ideas por presupuesto y por destinatario, cuándo comprar para que todo llegue a tiempo, y una herramienta gratis para organizar el amigo invisible sin dramas.',
        'secciones': [
            ('¿Cuándo es Navidad y Reyes 2026?',
             'Para que planifiques con fechas exactas: la <strong>Nochebuena es el jueves 24 de diciembre</strong>, <strong>Navidad el viernes 25</strong> y los <strong>Reyes Magos el miércoles 6 de enero de 2027</strong>. En Argentina son dos momentos de regalos: los adultos suelen intercambiar en Navidad, y a los más chicos les llegan los Reyes el 6 de enero. Si comprás online, la clave es una sola palabra: anticipación (más sobre eso al final).'),
            ('Regalos de Navidad por presupuesto',
             'Ordenado por lo que querés gastar. Con <strong>menos de $20.000</strong>: <a href="/coleccion/lamparas-y-luces-led/">luces LED</a> para decorar, accesorios de cocina, gadgets chicos. Entre <strong>$20.000 y $40.000</strong>: <a href="/coleccion/vasos-y-botellas-termicas/">vasos térmicos</a> para el mate del verano, veladores con diseño, <a href="/categoria/accesorios-de-moda/">bandoleras</a>. <strong>Más de $40.000</strong>: lámparas de escritorio, <a href="/coleccion/organizadores/">organizadores</a> grandes, o un combo de varias cosas. Mirá también las <a href="/categoria/ofertas/">ofertas de la semana</a> antes de decidir.',
             ('/assets/img/blog/regalos-de-navidad-por-presupuesto.jpg', 'Regalos de Navidad de distintos precios para elegir por presupuesto: vaso térmico, velador, bandolera y cajas de regalo')),
            ('Regalos de Navidad por destinatario',
             'Si ya sabés para quién es pero no qué: para <strong>ella</strong> tenemos una guía dedicada de <a href="/blog/regalos-originales-para-mujeres/">regalos originales para mujeres</a>; para <strong>él</strong>, la de <a href="/blog/regalos-originales-para-hombres/">regalos originales para hombres</a>. Para <strong>los más chicos</strong>, la sección de <a href="/categoria/articulos-infantiles/">artículos infantiles</a> tiene juguetes didácticos y regalos que entretienen sin pantalla — ideales también para dejar de parte de los Reyes.'),
            ('¿Amigo invisible en la oficina o la familia?',
             'El amigo invisible es el clásico navideño de grupos grandes: cada uno le regala a una sola persona y nadie gasta de más. Olvidate de los papelitos: usá nuestro <a href="/amigo-invisible/">amigo invisible online gratis</a>. Cargás los nombres y emails, sorteamos automáticamente (a nadie le sale su propio nombre), y cada uno recibe por email a quién le toca — con lista de deseos para no errarle e ideas de regalo del catálogo. Sin registro y sin trampas.'),
            ('Armá tu propia cajita navideña',
             'Las cajitas navideñas armadas se agotan y salen caras. La alternativa que queda mejor: armá la tuya combinando 2 o 3 productos que peguen entre sí. Por ejemplo, un <a href="/coleccion/vasos-y-botellas-termicas/">vaso térmico</a> + un paquete de café para el matero; unas <a href="/coleccion/lamparas-y-luces-led/">luces LED</a> + un detalle de <a href="/categoria/deco/">deco</a> para el que estrena casa. Sale más personal, más lindo y muchas veces más barato que la caja prearmada.',
             ('/assets/img/blog/cajita-navidena-armar-combo-regalo.jpg', 'Cajita navideña armada a mano con varios productos: una lámpara, un vaso térmico y luces LED, con papel y cinta amarilla')),
            ('Reyes Magos: los regalos del 6 de enero',
             'Después de Navidad viene la segunda ronda: el 6 de enero, los Reyes le dejan los regalos a los chicos. Si sos de los que dejan todo para último momento, esta vez anticipate: los <a href="/categoria/articulos-infantiles/">juguetes y artículos infantiles</a> más buscados se agotan entre Navidad y Reyes. Comprando en diciembre te asegurás el que querés y evitás el sobreprecio de última hora.'),
            ('El tip que salva la Navidad: comprá con tiempo',
             'El error más común es dejar los regalos para la semana del 20 de diciembre, justo cuando los envíos están saturados. Comprando online con anticipación tenés envío a todo el país con seguimiento y <strong>cambios hasta 10 días</strong> por si algo no era lo ideal. La regla simple: pedí antes del <strong>15 de diciembre</strong> y dormís tranquilo. Empezá por el <a href="/">catálogo completo</a> o directo por las <a href="/categoria/ofertas/">ofertas</a>.'),
        ],
        'faqs': [('¿Cuándo es Navidad 2026?',
                  'La Nochebuena es el jueves 24 de diciembre de 2026 y la Navidad el viernes 25. Los Reyes Magos llegan el miércoles 6 de enero de 2027.'),
                 ('¿Con cuánta anticipación conviene comprar los regalos de Navidad?',
                  'Lo ideal es comprar online antes del 15 de diciembre: los envíos se saturan la última semana y así te asegurás que todo llegue a tiempo, con margen para cambios si hiciera falta.'),
                 ('¿Cómo organizo el amigo invisible de Navidad?',
                  'Usá nuestro amigo invisible online gratis: cargás los participantes con su email, el sistema sortea automáticamente y le avisa a cada uno a quién le regala, con lista de deseos e ideas. Sin registro ni planillas.')],
    },
    'hot-sale-cyber-monday-black-friday': {
        'imagen': ('/assets/img/blog/hot-sale-cyber-monday-argentina.jpg', 'Persona comparando ofertas online en el celular y la notebook durante una jornada de descuentos como el Hot Sale'),
        'title': 'Hot Sale, Cyber Monday y Black Friday 2026 en Argentina: cuándo son | El Gadget',
        'h1': 'Hot Sale, Cyber Monday y Black Friday 2026: el calendario de ofertas argentino',
        'meta': 'Cuándo es el Hot Sale, el Cyber Monday y el Black Friday 2026 en Argentina, quién los organiza y cómo aprovechar los descuentos reales sin caer en precios inflados.',
        'fecha': '2026-07-13',
        'intro': 'Cada año hay tres momentos en los que las tiendas online argentinas se llenan de descuentos: el <strong>Hot Sale</strong>, el <strong>Cyber Monday</strong> y el <strong>Black Friday</strong>. Si querés aprovecharlos de verdad —y no picar el anzuelo de un precio inflado la semana anterior—, conviene saber cuándo son, quién los organiza y cómo comprar con cabeza. Acá va la guía completa, sin humo.',
        'secciones': [
            ('¿Qué son el Hot Sale, el Cyber Monday y el Black Friday?',
             'Los tres son eventos de descuentos, pero no son lo mismo. El <strong>Hot Sale</strong> y el <strong>Cyber Monday</strong> los organiza en Argentina la <strong>CACE</strong> (Cámara Argentina de Comercio Electrónico): son jornadas oficiales de varios días en las que cientos de tiendas adheridas publican ofertas al mismo tiempo. El <strong>Black Friday</strong> es de origen estadounidense (el viernes posterior al Día de Acción de Gracias) y en Argentina lo adoptan cada vez más comercios, aunque de forma menos coordinada. En los tres, la lógica es la misma: descuentos concentrados en pocos días para empujar las ventas.'),
            ('¿Cuándo son en Argentina en 2026?',
             'Las fechas exactas de los eventos de la CACE se confirman cada año, pero el patrón se repite: el <strong>Hot Sale suele caer en mayo</strong> y el <strong>Cyber Monday a principios de noviembre</strong>. El <strong>Black Friday 2026 es el viernes 27 de noviembre</strong> (sigue la fecha de Estados Unidos: el viernes después del cuarto jueves de noviembre), con el "Cyber Monday" estadounidense el lunes siguiente. En la práctica, esto arma una temporada fuerte de ofertas entre principios y fines de noviembre. Anotá esas ventanas y planificá con tiempo lo que querés comprar.',
             ('/assets/img/blog/cuando-es-el-hot-sale-planificar-compras.jpg', 'Escritorio con notebook, lista de compras y café para planificar las compras del Hot Sale y el Cyber Monday')),
            ('Cómo aprovechar los descuentos sin caer en precios inflados',
             'El truco más viejo de estas fechas es <strong>subir el precio semanas antes para "rebajarlo"</strong> durante el evento. Para no caer: <strong>1)</strong> armá la lista de lo que querés ANTES del evento y anotá su precio actual, así comparás contra el real y no contra el inflado. <strong>2)</strong> Usá comparadores o el historial de precios cuando puedas. <strong>3)</strong> Desconfiá de los "70% OFF" en productos que nunca costaron eso. <strong>4)</strong> Sumá el envío al total: a veces la "oferta" se come el descuento en el costo de envío. <strong>5)</strong> No compres por FOMO: si no lo ibas a comprar igual, no es ahorro, es gasto. Un buen descuento sobre algo que ya necesitabas es la única oferta que vale.',
             ('/assets/img/blog/descuentos-reales-hot-sale-comparar-precios.jpg', 'Manos comparando precios en el celular junto a paquetes de compras online, para detectar descuentos reales')),
            ('En El Gadget no hace falta esperar al Hot Sale',
             'Nuestra filosofía es la contraria a la del descuento inflado: preferimos <strong>precios reales todo el año</strong> antes que un "70% OFF" de mentira una vez por temporada. Por eso tenemos <a href="/categoria/ofertas/">ofertas rotativas toda la semana</a> —con el precio de lista siempre a la vista para que compares— y un calendario de descuentos por fecha que se activa en las temporadas clave. Si andás cazando una buena compra, no necesitás esperar a noviembre: mirá las <a href="/categoria/ofertas/">ofertas de esta semana</a> o el <a href="/">catálogo completo</a> cuando quieras.'),
            ('Qué conviene comprar en las fechas de descuento',
             'Los rubros que más rinden en estos eventos son los que combinan buen ticket y uso durable: <a href="/coleccion/lamparas-y-luces-led/">iluminación LED</a> para renovar ambientes, <a href="/coleccion/organizadores/">organizadores</a> para ordenar la casa, <a href="/coleccion/vasos-y-botellas-termicas/">vasos y botellas térmicas</a> para el mate y el gym, y <a href="/categoria/deco/">deco</a> para darle una vuelta a tu espacio. Si además estás por regalar, aprovechá para adelantarte a fechas como <a href="/blog/dia-del-amigo/">el Día del Amigo</a> o el Día de la Madre y comprá con descuento en vez de a las corridas.'),
        ],
        'faqs': [('¿Cuándo es el Hot Sale 2026 en Argentina?',
                  'El Hot Sale lo organiza la CACE y la fecha exacta se confirma cada año, pero suele realizarse en mayo. El Cyber Monday, también de la CACE, cae a principios de noviembre.'),
                 ('¿Cuándo es el Black Friday 2026?',
                  'El viernes 27 de noviembre de 2026. El Black Friday sigue la fecha de Estados Unidos: el viernes posterior al cuarto jueves de noviembre.'),
                 ('¿Los descuentos del Hot Sale son reales?',
                  'Muchos sí, pero conviene comparar: un truco común es subir el precio antes del evento para "rebajarlo" durante. Anotá el precio actual de lo que querés antes de que empiece y compará contra ese número, no contra el "precio anterior" que muestra la tienda.'),
                 ('¿El Gadget participa del Hot Sale?',
                  'Tenemos ofertas reales rotativas durante todo el año, con el precio de lista siempre visible para que compares. No hace falta esperar a una fecha puntual: mirá la sección de ofertas cuando quieras.')],
    },
    'como-curar-el-mate': {
        'imagen': ('/assets/img/blog/como-curar-el-mate.jpg', 'Mate de calabaza nuevo con bombilla y yerba sobre mesa de madera, listo para ser curado'),
        'title': 'Cómo Curar el Mate: calabaza, madera y todos los métodos (2026) | El Gadget',
        'h1': 'Cómo curar el mate: la guía definitiva paso a paso',
        'meta': 'Cómo curar un mate de calabaza o de madera paso a paso, por qué es necesario, qué mates no se curan y los errores que arruinan un mate nuevo.',
        'fecha': '2026-07-13',
        'intro': 'Te regalaron un mate nuevo (o te lo compraste) y alguien te dijo "primero hay que curarlo". Es verdad: curar el mate de calabaza o de madera es lo que define si te va a durar años con buen sabor o si se va a rajar y agriar en un mes. La buena noticia: lleva dos días y casi nada de trabajo. Acá va el método bien hecho, paso a paso.',
        'secciones': [
            ('¿Por qué hay que curar el mate?',
             'Los mates de calabaza y de madera son materiales porosos y "vivos": recién salidos del torno traen restos de pulpa, hollejos y sabores amargos. La cura hace tres cosas: <strong>limpia esos restos, sella los poros con la propia yerba y le da al mate su sabor de base</strong>. Un mate sin curar puede rajarse con el primer golpe de agua caliente y arruinar el sabor de cualquier yerba buena. Los cinco minutos que invertís hoy son años de mates ricos.'),
            ('Cómo curar un mate de calabaza, paso a paso',
             '<strong>1)</strong> Llená el mate con yerba usada (de una mateada anterior) hasta el borde. <strong>2)</strong> Agregá agua caliente —no hirviendo— hasta empapar todo y dejalo reposar 24 horas. <strong>3)</strong> Vaciá, raspá con cuchara SIN filo las paredes para quitar hollejos flojos (sin llegar a la cáscara), enjuagá solo con agua. <strong>4)</strong> Repetí el proceso una vez más, 24 horas. <strong>5)</strong> Enjuagá, secá con un paño y dejalo destapado hasta que esté completamente seco. Listo: tu calabaza está sellada y con base de sabor.',
             ('/assets/img/blog/curar-mate-calabaza-yerba-humeda.jpg', 'Mate de calabaza relleno de yerba húmeda durante el proceso de curado de 24 horas')),
            ('Cómo curar un mate de madera',
             'El proceso es el mismo que en la calabaza (yerba húmeda 24 horas, dos ciclos), con dos cuidados extra: la madera es más propensa a los hongos, así que el <strong>secado profundo entre ciclos es obligatorio</strong> (paño + aire, nunca guardado húmedo), y algunos materos untan una capa fina de manteca o aceite neutro en el exterior del palo santo o algarrobo antes de la primera cura, para hidratar la madera y evitar rajaduras. Si tu mate es de palo santo, esa pasada de aceite exterior le realza el aroma característico.'),
            ('¿Los mates de vidrio, cerámica o acero se curan?',
             'No. Los materiales no porosos —vidrio, cerámica esmaltada, acero inoxidable, silicona— <strong>no necesitan cura</strong>: un enjuague con agua caliente antes del primer uso y listo. Es su gran ventaja práctica (y por eso son ideales para el que quiere empezar a tomar mate sin ritual previo). La contra: nunca desarrollan el sabor propio que hace único a cada mate de calabaza.'),
            ('Cómo cebar un buen mate (ya que estamos)',
             'Mate curado merece cebada digna: yerba hasta 3/4, tapá con la mano, sacudí boca abajo (el polvillo queda arriba y no tapa la bombilla), acomodá la yerba en <strong>montañita a 45°</strong>, verté un chorrito de agua tibia en el hueco y esperá un minuto a que la yerba lo absorba. Recién ahí clavá la bombilla en el hueco y NO la muevas más. El agua ideal: <strong>75-80°C</strong>, nunca hervida — el termo o botella térmica la mantiene en ese punto exacto durante horas.',
             ('/assets/img/blog/como-cebar-un-buen-mate.jpg', 'Manos cebando un mate: agua caliente cayendo del termo sobre la montañita de yerba')),
            ('Los errores que arruinan un mate nuevo',
             'Los cuatro clásicos: <strong>agua hirviendo</strong> (raja la calabaza y quema la yerba), <strong>guardarlo húmedo o tapado</strong> (hongos garantizados — siempre destapado y seco), <strong>lavarlo con detergente o lavandina</strong> (los poros absorben el sabor químico para siempre: solo agua) y <strong>dejarlo con yerba vieja días enteros</strong> fuera del período de cura. Si ya apareció un punto de hongo: cucharada de bicarbonato con agua caliente, reposo, enjuague y secado al sol — y si está muy avanzado, es momento de un mate nuevo.'),
            ('El equipo del matero: el agua es la mitad del secreto',
             'Un buen mate necesita agua a temperatura constante: una <a href="/coleccion/vasos-y-botellas-termicas/">botella térmica de acero</a> mantiene los 75-80° ideales durante toda la mateada — serví con calma, sin pico cebador también funciona perfecto. Y para que el equipo dure años, ya te contamos <a href="/blog/como-limpiar-termo-acero-inoxidable/">cómo limpiar el termo de acero por dentro</a> (sarro y olor a mate viejo incluidos).',
             ('prod', r'botella t[ée]rmica')),
        ],
        'faqs': [('¿Cuánto tiempo lleva curar un mate?',
                  'Dos ciclos de 24 horas con yerba húmeda: en 48 horas más el secado final, tu mate de calabaza o madera está listo para la primera mateada real.'),
                 ('¿Se puede curar el mate con yerba nueva?',
                  'Sí, pero la yerba usada funciona mejor: ya liberó su amargor más agresivo y sella los poros con un sabor más redondo. Si solo tenés yerba nueva, humedecela bien con agua tibia antes.'),
                 ('¿Qué hago si mi mate quedó con gusto agrio o lavado?',
                  'Repetí un ciclo corto de cura (yerba húmeda 12 horas, raspado suave y secado profundo). Si el agrio persiste, revisá que no haya hongos en el fondo: bicarbonato, sol y paciencia.')],
    },
    'dia-del-amigo': {
        'imagen': ('/assets/img/blog/dia-del-amigo-argentina.jpg', 'Amigos brindando en una juntada al atardecer con luces cálidas por el Día del Amigo'),
        'title': 'Día del Amigo 2026: regalos, imágenes y amigo invisible gratis | El Gadget',
        'h1': 'Día del Amigo 2026: cuándo es y cómo celebrarlo',
        'meta': 'El Día del Amigo 2026 es el lunes 20 de julio. Regalos que no fallan, imágenes para saludar por WhatsApp y el sorteo de amigo invisible online gratis, sin registro.',
        'fecha': '2026-07-18',
        'intro': 'En Argentina, el Día del Amigo se festeja <strong>todos los 20 de julio</strong> — en 2026 cae lunes, así que la juntada se muda al fin de semana o se convierte en la excusa perfecta para arrancar la semana distinto. Acá tenés todo: imágenes para saludar al grupo, ideas de regalos y el plan que nunca falla. Y si con el grupo hacen intercambio de regalos, <strong><a href="/amigo-invisible/">sorteá el amigo invisible online gratis acá</a></strong>: cargás los nombres y cada uno recibe a quién le regala por email, sin registrarse y en 2 minutos.',
        'secciones': [
            ('¿Cuándo es el Día del Amigo y por qué el 20 de julio?',
             'El Día del Amigo argentino es el <strong>20 de julio, todos los años</strong> (no se mueve como el Día de la Madre). La fecha la propuso el rosarino Enrique Febbraro, que eligió el día de la llegada del hombre a la Luna en 1969 como símbolo de que la humanidad entera podía sentirse amiga. Ojo: no lo confundas con el Día Internacional de la Amistad de la ONU, que es el 30 de julio — acá el que vale es el 20.'),
            ('Imágenes de Feliz Día del Amigo para compartir',
             """<div style="display:grid;grid-template-columns:1fr 1fr;gap:14px;margin-top:6px;margin-bottom:10px"><div style="min-width:0"><img src="/assets/img/blog/feliz-dia-del-amigo-imagen-1.jpg" alt="Imagen de Feliz Día del Amigo para compartir por WhatsApp — luces doradas sobre fondo oscuro" width="1080" height="1080" loading="lazy" style="width:100%;height:auto;border-radius:12px;display:block"><div style="display:flex;flex-wrap:wrap;gap:6px;justify-content:center;margin-top:8px"><a class="btn btn-accent" style="padding:8px 14px;font-size:12.5px" href="https://wa.me/?text=%C2%A1Feliz%20D%C3%ADa%20del%20Amigo!%20%F0%9F%A7%89%20https%3A%2F%2Felgadget.com.ar%2Fassets%2Fimg%2Fblog%2Ffeliz-dia-del-amigo-imagen-1.jpg" target="_blank" rel="noopener">Compartir 💬</a><a class="btn" style="padding:8px 14px;font-size:12.5px;border:1.5px solid var(--gray-200);color:var(--ink)" href="/assets/img/blog/feliz-dia-del-amigo-imagen-1.jpg" download>Descargar ⬇️</a></div></div><div style="min-width:0"><img src="/assets/img/blog/feliz-dia-del-amigo-imagen-2.jpg" alt="Imagen de Feliz Día del Amigo para compartir por WhatsApp — mates brindando, estilo divertido" width="1080" height="1080" loading="lazy" style="width:100%;height:auto;border-radius:12px;display:block"><div style="display:flex;flex-wrap:wrap;gap:6px;justify-content:center;margin-top:8px"><a class="btn btn-accent" style="padding:8px 14px;font-size:12.5px" href="https://wa.me/?text=%C2%A1Feliz%20D%C3%ADa%20del%20Amigo!%20%F0%9F%A7%89%20https%3A%2F%2Felgadget.com.ar%2Fassets%2Fimg%2Fblog%2Ffeliz-dia-del-amigo-imagen-2.jpg" target="_blank" rel="noopener">Compartir 💬</a><a class="btn" style="padding:8px 14px;font-size:12.5px;border:1.5px solid var(--gray-200);color:var(--ink)" href="/assets/img/blog/feliz-dia-del-amigo-imagen-2.jpg" download>Descargar ⬇️</a></div></div><div style="min-width:0"><img src="/assets/img/blog/feliz-dia-del-amigo-imagen-3.jpg" alt="Imagen de Feliz Día del Amigo para compartir por WhatsApp — asado argentino de fondo" width="1080" height="1080" loading="lazy" style="width:100%;height:auto;border-radius:12px;display:block"><div style="display:flex;flex-wrap:wrap;gap:6px;justify-content:center;margin-top:8px"><a class="btn btn-accent" style="padding:8px 14px;font-size:12.5px" href="https://wa.me/?text=%C2%A1Feliz%20D%C3%ADa%20del%20Amigo!%20%F0%9F%A7%89%20https%3A%2F%2Felgadget.com.ar%2Fassets%2Fimg%2Fblog%2Ffeliz-dia-del-amigo-imagen-3.jpg" target="_blank" rel="noopener">Compartir 💬</a><a class="btn" style="padding:8px 14px;font-size:12.5px;border:1.5px solid var(--gray-200);color:var(--ink)" href="/assets/img/blog/feliz-dia-del-amigo-imagen-3.jpg" download>Descargar ⬇️</a></div></div><div style="min-width:0"><img src="/assets/img/blog/feliz-dia-del-amigo-imagen-4.jpg" alt="Imagen de Feliz Día del Amigo para compartir por WhatsApp — mensaje gracias por estar siempre" width="1080" height="1080" loading="lazy" style="width:100%;height:auto;border-radius:12px;display:block"><div style="display:flex;flex-wrap:wrap;gap:6px;justify-content:center;margin-top:8px"><a class="btn btn-accent" style="padding:8px 14px;font-size:12.5px" href="https://wa.me/?text=%C2%A1Feliz%20D%C3%ADa%20del%20Amigo!%20%F0%9F%A7%89%20https%3A%2F%2Felgadget.com.ar%2Fassets%2Fimg%2Fblog%2Ffeliz-dia-del-amigo-imagen-4.jpg" target="_blank" rel="noopener">Compartir 💬</a><a class="btn" style="padding:8px 14px;font-size:12.5px;border:1.5px solid var(--gray-200);color:var(--ink)" href="/assets/img/blog/feliz-dia-del-amigo-imagen-4.jpg" download>Descargar ⬇️</a></div></div></div>Elegí la que más le pegue a tu grupo: tocá <strong>Compartir</strong> y llega directo por WhatsApp, o descargala para subirla a tus historias. Gratis, de nuestra parte 💛"""),
            ('Regalos para el Día del Amigo que no fallan',
             'Entre amigos, el regalo perfecto es el que se usa en las juntadas: un <a href="/coleccion/vasos-y-botellas-termicas/">vaso térmico</a> para el mate compartido o la cerveza del asado, unas <a href="/coleccion/lamparas-y-luces-led/">luces LED</a> para el balcón de las previas, o algún <a href="/categoria/electronica/">gadget divertido</a> que se convierta en el chiste interno del grupo. Y si son de jugar al amigo invisible, más abajo te contamos cómo organizarlo.',
             ('/assets/img/blog/regalos-dia-del-amigo-ideas.jpg', 'Ideas de regalos para el Día del Amigo: vaso térmico, luces LED, gadget divertido, mate y caja de regalo con cinta amarilla')),
            ('Ideas por presupuesto',
             'Con <strong>menos de $20.000</strong>: luces LED, accesorios de cocina para el asador del grupo, gadgets chicos. Entre <strong>$20.000 y $40.000</strong>: vasos térmicos, veladores con onda, alfombras de diatomita para el amigo que se acaba de mudar. <strong>Más de $40.000</strong>: la lámpara 3-en-1 de escritorio o un combo de varias cosas chicas para repartir sonrisas. Mirá las <a href="/categoria/ofertas/">ofertas de la semana</a> antes de decidir.'),
            ('¿Amigo invisible? Cómo organizarlo sin dramas',
             'El amigo invisible (o "amigo secreto") es el formato ideal para grupos grandes: cada uno le regala a una sola persona y nadie gasta de más. Tip de oro: fijen el presupuesto ANTES de sortear — evita el clásico "yo le regalé más". Y para el sorteo, no hagas papelitos: usá nuestro <a href="/amigo-invisible/">amigo invisible online gratis</a>. Cargás los nombres y emails, sorteamos automáticamente (a nadie le sale su propio nombre) y cada uno recibe por email a quién le toca, con lista de deseos e ideas de regalo. Sin registro, sin trampas.'),
            ('El plan que nunca falla: la juntada',
             'El mejor regalo del 20 de julio sigue siendo la mesa compartida: asado, pizzas o mate con bizcochos, luces cálidas y sobremesa larga. Si este año te toca ser anfitrión, un par de <a href="/coleccion/lamparas-y-luces-led/">guirnaldas o luces cálidas</a> transforman cualquier balcón en el lugar de la foto grupal. Feliz día para vos y los tuyos 💛'),
        ],
        'faqs': [('¿Cuándo es el Día del Amigo 2026 en Argentina?',
                  'El lunes 20 de julio de 2026. En Argentina es siempre el 20 de julio, en conmemoración de la llegada del hombre a la Luna (1969).'),
                 ('¿El Día del Amigo y el Día de la Amistad son lo mismo?',
                  'No: el Día del Amigo argentino es el 20 de julio; el Día Internacional de la Amistad declarado por la ONU es el 30 de julio. En Argentina se festeja el 20.'),
                 ('¿Llego a comprar un regalo online para el 20 de julio?',
                  'Depende de tu zona: el checkout te muestra la demora estimada de envío. Como regla general, comprando con una semana de anticipación llegás cómodo a todo el país.')],
    },
    'regalos-dia-de-la-madre': {
        'imagen': ('/assets/img/blog/regalos-dia-de-la-madre-argentina.jpg', 'Regalos envueltos en papel kraft con cintas amarillas y flores frescas sobre una mesa, listos para el Día de la Madre'),
        'title': 'Día de la Madre 2026 en Argentina: cuándo es y 12 ideas de regalos | El Gadget',
        'h1': 'Día de la Madre 2026: cuándo es y qué regalar',
        'meta': 'El Día de la Madre 2026 en Argentina es el domingo 18 de octubre. 12 ideas de regalos útiles y originales por presupuesto, con envío a todo el país.',
        'fecha': '2026-07-12',
        'intro': 'En Argentina, el Día de la Madre se celebra el tercer domingo de octubre: en 2026 cae el <strong>domingo 18 de octubre</strong>. Si este año querés llegar con un regalo pensado (y no comprado a las corridas el sábado a la noche), acá van 12 ideas útiles y originales, organizadas por tipo de mamá y por presupuesto.',
        'secciones': [
            ('¿Por qué en Argentina se festeja en octubre?',
             'A diferencia de casi todo el mundo (que lo celebra en mayo), Argentina mantiene la fecha de octubre por la tradición católica de la Maternidad de la Virgen, que el calendario litúrgico ubicaba el 11 de octubre. Aunque la Iglesia movió su fecha, la costumbre comercial y familiar quedó: acá, el tercer domingo de octubre es sagrado. Anotalo: <strong>18 de octubre de 2026</strong>.'),
            ('Regalos útiles que va a usar todos los días',
             'Los regalos que más se agradecen son los que entran en la rutina: un <a href="/coleccion/vasos-y-botellas-termicas/">vaso térmico con tapa</a> para el café o el mate de la mañana (el clásico que no falla), una <a href="/coleccion/vasos-y-botellas-termicas/">botella térmica</a> para el agua del día, o esa <a href="/categoria/bazar-y-cocina/">solución de cocina</a> que le ahorre diez minutos diarios. Cada vez que lo use, se va a acordar de quién se lo regaló — ese es el verdadero truco del regalo útil.',
             ('/assets/img/blog/regalo-dia-de-la-madre-vaso-termico-mate.jpg', 'Vaso térmico de acero y mate argentino sobre la mesada de una cocina luminosa, un regalo útil para el Día de la Madre')),
            ('Para la mamá que ama su casa',
             'Si lo suyo es el hogar: un <a href="/coleccion/lamparas-y-luces-led/">velador LED con diseño</a> para la mesa de luz (los de efecto infinito espejado son los más regalados del catálogo), un <a href="/categoria/deco/">espejo decorativo</a> que agrande el living, o un detalle de <a href="/categoria/deco/">deco</a> que renueve el ambiente sin obras. Son regalos que se ven todos los días.',
             ('/assets/img/blog/regalo-mama-velador-led-mesa-de-luz.jpg', 'Velador LED con luz cálida encendido en la mesa de luz de un dormitorio acogedor, idea de regalo para mamá')),
            ('Para la mamá con estilo',
             'Una <a href="/categoria/accesorios-de-moda/">bandolera tejida o cartera</a> nueva para el día a día — liviana, cómoda y con onda — o algún <a href="/categoria/estetica-y-belleza/">accesorio de belleza</a> para su rutina. Y si tu mamá es de las que cuentan los días para las vacaciones, una <a href="/coleccion/mallas-y-trajes-de-bano/">malla nueva</a> es anticipar el verano: con cambios hasta 10 días, el talle no es riesgo.',
             ('prod', r'bandolera tejida')),
            ('Para la mamá organizada (o la que sueña con serlo)',
             'Los <a href="/coleccion/organizadores/">organizadores</a> son el regalo sorpresa: nadie los pide, todas los terminan amando. Un zapatero que libere el recibidor, cajoneras para el placard o el organizador de baúl para el auto. Regalar orden es regalar tiempo — y a una mamá, el tiempo es el regalo más escaso.',
             ('prod', r'zapatero')),
            ('Para la mamá de la mascota de la familia',
             'Si en tu casa el perro o el gato también es hijo: una <a href="/categoria/accesorios-para-mascotas/">alfombra absorbente para el comedero</a> (chau piso mojado), el guante quita-pelos que salva sillones, o un bebedero portátil para los paseos. Regalo para ella, beneficio para toda la casa.',
             ('prod', r'alfombra absorbente')),
            ('Ideas por presupuesto',
             'Con <strong>menos de $20.000</strong>: accesorios de cocina, jaboneras y organizadores chicos, luces LED con sensor. Entre <strong>$20.000 y $40.000</strong>: veladores de diseño, bandoleras, alfombras de diatomita, vasos térmicos. <strong>Más de $40.000</strong>: lámparas de escritorio 3-en-1, mallas, organizadores grandes o armá un combo de dos o tres cosas chicas — el efecto "abrió tres regalos" nunca falla.',
             ('/assets/img/blog/ideas-regalos-dia-de-la-madre-por-presupuesto.jpg', 'Ideas de regalos para el Día de la Madre por presupuesto: bandolera tejida, vaso térmico, velador y caja de regalo con cinta amarilla')),
            ('El tip para no fallar: comprá con tiempo',
             'Comprando online con anticipación tenés envío a todo el país con seguimiento y <strong>cambios hasta 10 días</strong> después de recibido: si el color o el talle no eran los ideales, se cambia sin drama. Pedilo la primera quincena de octubre y llegás sin pagar el apuro. Mirá el <a href="/">catálogo completo</a> o directo las <a href="/categoria/ofertas/">ofertas de la semana</a>.'),
        ],
        'faqs': [('¿Cuándo es el Día de la Madre 2026 en Argentina?',
                  'El domingo 18 de octubre de 2026. En Argentina siempre se celebra el tercer domingo de octubre, a diferencia de la mayoría de los países que lo festejan en mayo.'),
                 ('¿Qué regalar si no conozco sus gustos?',
                  'Andá por lo útil: vasos térmicos, organizadores o un velador con diseño funcionan para casi cualquier mamá. Y con cambios hasta 10 días, el riesgo es cero.'),
                 ('¿Hasta cuándo puedo comprar online para que llegue a tiempo?',
                  'Depende de tu zona: los envíos se calculan en el checkout con su demora estimada. Como regla general, comprá antes del 10 de octubre y llegás cómodo a cualquier punto del país.')],
    },
    'regalos-originales-para-mujeres': {
        'imagen': ('/assets/img/blog/regalos-originales-para-mujeres.jpg', 'Composición de regalos originales para mujeres: bandolera tejida, velador cálido, vaso térmico y caja de regalo con cinta amarilla'),
        'title': 'Regalos Originales para Mujeres: 12 ideas útiles (2026) | El Gadget',
        'h1': 'Regalos originales para mujeres: ideas que no fallan',
        'meta': '12 ideas de regalos originales para mujeres: útiles, con onda y por presupuesto. Para cumpleaños, aniversarios o porque sí. Envío a todo el país.',
        'fecha': '2026-07-12',
        'intro': 'Encontrar un regalo original para una mujer que "ya tiene todo" es un clásico problema. La clave no es gastar más: es regalar algo que use, que la sorprenda o que mejore un rato de su día. Estas 12 ideas funcionan para cumpleaños, aniversarios, el intercambio de fin de año o el simple "vi esto y me acordé de vos".',
        'secciones': [
            ('El error clásico (y cómo evitarlo)',
             'El regalo genérico — la vela, el jabón decorativo, el marco de fotos — dice "cumplí con el compromiso". El regalo que funciona dice "pensé en vos": parte de algo que ella hace todos los días y lo mejora. Por eso las ideas de esta lista están organizadas por rutina, no por producto. Pensá en su día típico y el regalo aparece solo.'),
            ('Para la que vive a mate y café',
             'Un <a href="/coleccion/vasos-y-botellas-termicas/">vaso térmico con tapa</a> la acompaña del escritorio al auto sin que se enfríe el café, y el de vidrio doble pared es el favorito de las cafeteras de especialidad. Si es más de hidratarse, una <a href="/coleccion/vasos-y-botellas-termicas/">botella térmica</a> de acero la sigue al gym, la facu o la oficina. Es de esos regalos que se usan a diario — y cada uso te menciona.',
             ('/assets/img/blog/regalo-original-mujer-vaso-termico-cafe.jpg', 'Vaso de vidrio doble pared con café con leche sobre un escritorio luminoso, regalo original para mujeres que aman el café')),
            ('Para la que ama su espacio',
             'Un <a href="/coleccion/lamparas-y-luces-led/">velador LED de diseño</a> (los de efecto infinito espejado son los más regalados), un <a href="/categoria/deco/">espejo decorativo</a> que duplique la luz de su ambiente favorito, o un detalle de <a href="/categoria/deco/">deco con personalidad</a>. La que disfruta su casa valora más un objeto que la mejore que cualquier cosa para "guardar".'),
            ('Para la que siempre está en movimiento',
             'Una <a href="/categoria/accesorios-de-moda/">bandolera tejida</a> con onda para salir liviana, una riñonera urbana para el día largo, o una cartera con más lugar. Manos libres, estilo y uso garantizado. Las fichas tienen fotos reales y medidas — elegí según su estilo, no según el apuro.',
             ('/assets/img/blog/regalo-mujer-bandolera-tejida.jpg', 'Bandolera tejida al crochet y riñonera urbana colgadas de un perchero de madera, regalos originales para mujeres en movimiento')),
            ('Para la organizada (o la que quiere serlo)',
             'Los <a href="/coleccion/organizadores/">organizadores</a> son el regalo sorpresa: nadie los pide, todas los terminan amando. Cajoneras para el placard, colgantes para la cocina, el zapatero que libera el recibidor. Regalar orden es regalar espacio mental.'),
            ('Para la que ya está pensando en el verano',
             'Una <a href="/coleccion/mallas-y-trajes-de-bano/">malla nueva</a> — enteriza que estiliza o bikini de tiro alto — anticipa las vacaciones en cualquier mes del año. Con la tabla de talles de cada ficha y cambios hasta 10 días, es un regalo mucho menos arriesgado de lo que parece. Y si tiene pileta, un <a href="/coleccion/inflables-para-pileta/">inflable gigante</a> es la sorpresa divertida.',
             ('/assets/img/blog/regalo-mujer-malla-verano.jpg', 'Malla enteriza sobre toalla de rayas con sombrero de paja y anteojos de sol, regalo de verano para mujeres')),
            ('Ideas por presupuesto',
             'Con <strong>menos de $20.000</strong>: accesorios de belleza, organizadores chicos, luces LED. Entre <strong>$20.000 y $40.000</strong>: bandoleras, veladores de diseño, vasos térmicos, alfombras de diatomita para el baño. <strong>Más de $40.000</strong>: mallas, lámparas 3-en-1 de escritorio, o un combo de varias cosas chicas que se abren una por una.'),
        ],
        'faqs': [('¿Qué regalo original conviene si no sé su talle?',
                  'Evitá ropa y andá por accesorios, deco o térmicos: no tienen talle y no fallan. Y si elegís una cartera o malla, hay cambios hasta 10 días.'),
                 ('¿Hacen envíos para regalos a otra dirección?',
                  'Sí: en el checkout ponés la dirección de entrega que quieras y llega a todo el país con seguimiento por email.'),
                 ('¿Qué regalar para un cumpleaños de último momento?',
                  'Elegí algo de su rutina diaria (térmico, velador, bandolera) y comprá ya: el envío tiene demora estimada visible en el checkout. Para zonas cercanas suele llegar en pocos días.')],
    },
    'regalos-originales-para-hombres': {
        'imagen': ('/assets/img/blog/regalos-originales-para-hombres.jpg', 'Regalos originales para hombres sobre fondo gris: vaso térmico de acero, gadget, lámpara de escritorio y caja kraft con cinta amarilla'),
        'title': 'Regalos Originales para Hombres: 12 ideas útiles (2026) | El Gadget',
        'h1': 'Regalos originales para hombres: ideas que sí va a usar',
        'meta': '12 ideas de regalos originales para hombres: gadgets, térmicos y accesorios útiles para cumpleaños, Día del Padre o Navidad. Envío a todo el país.',
        'fecha': '2026-07-12',
        'intro': 'El problema con regalarle a un hombre no es la falta de opciones: es que la mitad de los regalos terminan en un cajón. La solución es simple — regalá cosas que se usan. Estas 12 ideas funcionan para cumpleaños, Día del Padre, Navidad o amigo invisible, organizadas por tipo de tipo.',
        'secciones': [
            ('La regla de oro: utilidad primero',
             'Los hombres son el público más fácil de conformar y el más difícil de sorprender. El truco: no busques "el regalo perfecto", buscá el objeto que mejora algo que él ya hace — tomar mate, ordenar el auto, armar su escritorio. La sorpresa no está en el objeto raro sino en que alguien haya mirado su rutina con atención.'),
            ('Para el del mate, el café o la cerveza',
             'El <a href="/coleccion/vasos-y-botellas-termicas/">vaso térmico</a> es el regalo masculino infalible de los últimos años: frío que dura horas para la cerveza del asado, calor para el café del lunes. Hay desde el clásico Stanley de 480ml con tapa hasta el gigante de 1200ml con agarre que banca el día entero. Si ya tiene vaso, la <a href="/coleccion/vasos-y-botellas-termicas/">botella térmica</a> de acero es el paso dos.',
             ('/assets/img/blog/regalo-hombre-vaso-termico-asado.jpg', 'Vaso térmico de acero junto a la parrilla de un quincho argentino al atardecer, regalo para hombres')),
            ('Para el fierrero (o el desordenado)',
             'El <a href="/coleccion/organizadores/">bolso organizador de baúl</a> transforma el auto: herramientas, compras y equipamiento, cada cosa en su lugar y sin ruidos en cada curva. Es uno de esos regalos que "no sabía que necesitaba" y termina recomendando a los amigos. Sumale el zapatero vertical si su placard es zona de guerra.',
             ('/assets/img/blog/regalo-hombre-organizador-baul-auto.jpg', 'Baúl de auto ordenado con bolso organizador plegable con herramientas y elementos de viaje')),
            ('Para el gamer o el tecnológico',
             'Algún <a href="/categoria/electronica/">gadget electrónico</a> útil o la <a href="/coleccion/lamparas-y-luces-led/">lámpara LED de escritorio</a> con ventilador USB y reloj — el 3-en-1 del home office y el setup gamer. Funcional, con onda, y sin el riesgo de regalarle un periférico que ya tiene mejor.',
             ('prod', r'lampara led escritorio|l[áa]mpara led escritorio')),
            ('Para el que entrena (o dice que va a empezar)',
             'Los <a href="/categoria/fitness/">accesorios fitness</a> para entrenar en casa eliminan la excusa del gimnasio, y una <a href="/coleccion/vasos-y-botellas-termicas/">botella térmica</a> mantiene el agua helada hasta la última serie. Regalo doble mensaje: te apoyo, y no tenés más excusas.',
             ('prod', r'botella t[ée]rmica')),
            ('Para el papá perro (o gato)',
             'Si su mascota es su copiloto: el <a href="/categoria/accesorios-para-mascotas/">guante quita-pelos</a> que salva el asiento del auto y el sillón, el bebedero portátil para las salidas, o la alfombra absorbente para la zona del comedero. Práctico y con puntos extra de ternura.',
             ('prod', r'guante removedor|guante.*pelos')),
            ('Ideas por presupuesto',
             'Con <strong>menos de $20.000</strong>: gadgets chicos, luces LED con sensor, accesorios para el auto. Entre <strong>$20.000 y $40.000</strong>: vasos térmicos, organizadores de baúl, accesorios fitness. <strong>Más de $40.000</strong>: lámparas de escritorio 3-en-1, botellas térmicas grandes, o el combo térmico + organizador que nunca falla.'),
            ('¿Cuándo es el Día del Padre?',
             'En Argentina, el <strong>tercer domingo de junio</strong>. Si llegaste tarde este año, anotalo para el próximo — o mejor: regalale algo hoy "porque sí". Los regalos sin fecha son los que más se recuerdan. Mirá las <a href="/categoria/ofertas/">ofertas de la semana</a> para aprovechar el momento.'),
        ],
        'faqs': [('¿Qué regalar para el Día del Padre?',
                  'En Argentina cae el tercer domingo de junio. Los térmicos, el organizador de baúl y los gadgets de escritorio son los más regalados — todos con envío a domicilio y cambios hasta 10 días.'),
                 ('¿Qué le regalo a un hombre que dice que no necesita nada?',
                  'El que "no necesita nada" es el candidato ideal para el regalo de rutina mejorada: un térmico mejor que el que usa, orden para el auto que ya tiene. No es necesitar: es mejorar lo que ya hace.'),
                 ('¿Puedo mandar el regalo directo a su casa?',
                  'Sí: en el checkout cargás su dirección y le llega con seguimiento. Ideal para sorpresas a distancia.')],
    },
    'como-limpiar-termo-acero-inoxidable': {
        'imagen': ('/assets/img/blog/como-limpiar-termo-acero-inoxidable.jpg', 'Termo de acero inoxidable destapado junto a cepillo para botellas, vinagre blanco y bicarbonato sobre la mesada'),
        'title': 'Cómo Limpiar un Termo de Acero Inoxidable por Dentro (sarro y olores) | El Gadget',
        'h1': 'Cómo limpiar un termo de acero inoxidable por dentro',
        'meta': 'Guía completa para limpiar un termo de acero inoxidable por dentro: sacar el sarro, eliminar olores y qué NO usar nunca. Métodos caseros que funcionan.',
        'fecha': '2026-07-13',
        'intro': 'El termo de acero inoxidable es de esos objetos que usamos todos los días y limpiamos… cuando nos acordamos. El problema: el sarro y el olor a mate viejo se acumulan por dentro, donde la esponja no llega. La buena noticia es que limpiarlo bien lleva 10 minutos con cosas que ya tenés en la cocina — y hay dos o tres errores que pueden arruinarlo para siempre.',
        'secciones': [
            ('La limpieza básica (una vez por semana)',
             'Agua bien caliente, unas gotas de detergente, tapá y agitá 30 segundos. Para llegar al fondo, un <a href="/categoria/bazar-y-cocina/">cepillo flexible para botellas</a> hace la diferencia: las cerdas de silicona limpian las paredes sin rayar el acero. Enjuagá dos veces y dejá secar SIEMPRE destapado y boca abajo — el 80% de los olores nacen de guardarlo húmedo y cerrado.',
             ('prod', r'cepillo flexible')),
            ('Cómo sacar el sarro del termo',
             'El sarro (esas manchas blancas o marrones del fondo) sale con vinagre blanco: llená un tercio del recipiente con vinagre, completá con agua caliente, dejá actuar 30-60 minutos y cepillá el fondo. Para sarro rebelde, el combo bicarbonato + vinagre: dos cucharadas de bicarbonato, medio vaso de vinagre, dejalo burbujear destapado 15 minutos, cepillo y enjuague. El acero inoxidable queda como nuevo sin ningún producto agresivo.',
             ('/assets/img/blog/limpiar-sarro-termo-vinagre-bicarbonato.jpg', 'Interior de un termo de acero inoxidable con espuma de bicarbonato y vinagre burbujeando')),
            ('Cómo quitar el olor de un termo',
             'Si el termo quedó con olor a mate de ayer (o a café de la semana pasada): bicarbonato y agua caliente toda la noche, destapado. Para olores persistentes, el truco del arroz: un puñado de arroz crudo, un chorro de vinagre y agua tibia — tapá y agitá fuerte un minuto; el arroz hace de esponja abrasiva suave donde nada más llega. Enjuague doble y secado destapado.'),
            ('Lo que NUNCA hay que hacerle a un termo de acero',
             'cuatro errores fatales: lavandina (pica el acero inoxidable y deja olor químico), esponja de acero o virulana por dentro (raya y ahí anida el sarro), lavavajillas (el calor del ciclo puede arruinar el vacío térmico del doble pared) y meterlo al freezer (mismo problema, al revés). Si el tuyo dejó de mantener la temperatura después de un lavavajillas, ya sabés qué pasó.'),
            ('¿Por qué mi termo ya no mantiene el calor?',
             'Un termo de doble pared funciona por el vacío entre sus paredes. Si recibió un golpe fuerte, pasó por el lavavajillas o el freezer, ese vacío puede perderse — y no tiene arreglo: se convierte en una botella común. La prueba: servile agua caliente; si la pared exterior se calienta, perdió el vacío. En ese caso, es momento de renovarlo — mirá los <a href="/coleccion/vasos-y-botellas-termicas/">vasos y botellas térmicas</a> del catálogo, con doble pared de acero real.'),
            ('La rutina que lo hace durar años',
             'Enjuague con agua caliente después de cada uso (30 segundos), lavado con detergente y cepillo una vez por semana, vinagre contra el sarro una vez por mes si tomás mate o café a diario, y secado siempre destapado. Con esa rutina mínima, uno de buena calidad dura años manteniendo el frío y el calor como el primer día.',
             ('/assets/img/blog/secar-termo-destapado-boca-abajo.jpg', 'Termos y vaso térmico de acero secándose boca abajo destapados sobre un paño junto a la bacha')),
        ],
        'faqs': [('¿Se puede lavar un termo de acero inoxidable en el lavavajillas?',
                  'No, salvo que el fabricante lo indique expresamente. El calor del ciclo puede dañar el vacío de la doble pared y las juntas de la tapa: el termo deja de mantener la temperatura.'),
                 ('¿Cada cuánto hay que limpiar el termo por dentro?',
                  'Enjuague diario, lavado con detergente semanal y limpieza profunda con vinagre una vez por mes si lo usás todos los días para mate o café.'),
                 ('¿El sarro del termo hace mal a la salud?',
                  'El sarro es principalmente carbonato de calcio del agua: no es tóxico, pero da mal sabor y aloja bacterias si se acumula. Conviene sacarlo apenas aparece.')],
    },
    'como-organizar-el-placard': {
        'imagen': ('/assets/img/blog/como-organizar-el-placard.jpg', 'Placard organizado con perchas iguales, cajas de tela y doblado vertical en cajones'),
        'title': 'Cómo Organizar el Placard: método simple en 5 pasos | El Gadget',
        'h1': 'Cómo organizar el placard (y que se mantenga ordenado)',
        'meta': 'Método práctico para organizar el placard en 5 pasos: qué sacar, cómo agrupar, dónde van los zapatos y qué organizadores usar para que el orden dure.',
        'fecha': '2026-07-11',
        'intro': 'Organizar el placard no es tirar todo y doblar mejor: es armar un sistema que se mantenga solo. Este método de 5 pasos funciona en placards grandes y chicos, y al final te decimos qué accesorios ayudan de verdad (y cuáles son puro chiche).',
        'secciones': [
            ("Deslizá: el antes y el después", """<div style="position:relative;max-width:640px;margin:0 auto 10px;border-radius:12px;overflow:hidden"><img src="/assets/img/blog/placard-organizado-despues.jpg" alt="El mismo placard organizado después del método" width="1200" height="670" style="display:block;width:100%;height:auto"><img src="/assets/img/blog/placard-desordenado-antes.jpg" alt="Placard desordenado antes de aplicar el método" width="1200" height="670" style="position:absolute;inset:0;width:100%;height:auto;clip-path:inset(0 50% 0 0)"><span style="position:absolute;top:10px;left:10px;background:rgba(20,21,26,.78);color:#fff;font-size:11px;font-weight:700;padding:4px 10px;border-radius:12px;letter-spacing:1px">ANTES</span><span style="position:absolute;top:10px;right:10px;background:rgba(20,21,26,.78);color:#FFC700;font-size:11px;font-weight:700;padding:4px 10px;border-radius:12px;letter-spacing:1px">DESPUÉS</span><input type="range" min="0" max="100" value="50" aria-label="Comparar antes y después" oninput="this.parentElement.querySelectorAll('img')[1].style.clipPath='inset(0 '+(100-this.value)+'% 0 0)'" style="position:absolute;left:4%;right:4%;bottom:8px;width:92%;accent-color:#FFC700;cursor:ew-resize"></div>Deslizá para comparar: el mismo placard aplicando este método, sin comprar un mueble nuevo."""),
            ('Paso 1 y 2: vaciar y decidir',
             'Sacá todo — sí, todo — y armá tres pilas: uso, no uso pero guardo, y se va. Sé honesto: lo que no usaste en un año no lo vas a usar. El placard ordenado empieza con menos cosas, no con más ganchos.'),
            ('Paso 3: agrupar por frecuencia, no por tipo',
             'Lo de todos los días a la altura de los ojos; lo de temporada arriba; lo ocasional abajo. El error clásico es agrupar "todas las camperas juntas" aunque uses una sola: el orden útil sigue tu rutina, no la lógica del catálogo.'),
            ('Paso 4: los zapatos, el jefe final',
             'Los zapatos sueltos destruyen cualquier placard. Un <a href="/coleccion/organizadores/">zapatero abatible</a> los saca del piso y los esconde en el espesor de un cuadro — ideal para recibidores y espacios chicos. Si van dentro del placard, las cajoneras con ruedas aprovechan el piso muerto.',
             ('/assets/img/blog/organizar-zapatos-zapatero-recibidor.jpg', 'Zapatero vertical delgado en un recibidor pequeño y luminoso con espejo, zapatos organizados')),
            ('Paso 5: sistemas que se mantienen solos',
             'La regla de oro: cada cosa necesita UN lugar obvio. Los <a href="/coleccion/organizadores/">organizadores colgantes y plegables</a> crean esos lugares sin obras ni muebles nuevos. Si guardar algo cuesta más de 5 segundos, el sistema falló — simplificá.',
             ('prod', r'colgante de puerta|organizador colgante')),
            ('Ordenar el placard por temporada',
             'El placard rinde el doble si solo contiene la temporada actual. Lo de invierno en verano (y viceversa) va arriba o abajo, en cajas o en un <a href="/coleccion/organizadores/">organizador plegable</a> rotulado. Dos rotaciones al año — abril y octubre — y de paso repasás el paso 2: lo que no usaste en toda la temporada, se va.',
             ('/assets/img/blog/ordenar-placard-por-temporada-cajas.jpg', 'Cajas organizadoras de tela con ropa de invierno en el estante superior del placard')),
            ('Closet pequeño: reglas de oro',
             'En un closet pequeño cada centímetro cuenta: perchas todas iguales (ocupan menos y se ve ordenado), doblado vertical en cajones para ver todo de frente, y la puerta como territorio útil con un colgante de puerta. La regla de entrada: si entra algo nuevo, sale algo viejo.'),
        ],
        'faqs': [('¿Cómo organizo un placard chico?',
                  'Verticalidad: colgantes de puerta, estantes divididos y cajoneras apilables. En placards chicos el aire entre estantes es el espacio más desperdiciado.'),
                 ('¿Cómo organizar los zapatos si no tengo lugar?',
                  'Zapatero vertical abatible: ocupa 20cm de profundidad contra la pared. Guarda pares de toda la familia en el espacio de un espejo de pie.')],
    },
    'como-organizar-una-cocina-pequena': {
        'imagen': ('/assets/img/blog/como-organizar-una-cocina-pequena.jpg', 'Cocina pequeña organizada con mesada despejada, organizadores colgantes y frascos alineados'),
        'title': 'Cómo Organizar una Cocina Pequeña: 7 trucos que liberan espacio | El Gadget',
        'h1': 'Cómo organizar una cocina pequeña sin obras',
        'meta': 'Trucos concretos para organizar una cocina pequeña: paredes, alturas, mesada libre y los organizadores que sí funcionan. Sin obras ni gastar de más.',
        'fecha': '2026-07-11',
        'intro': 'Una cocina pequeña no necesita más muebles: necesita usar mejor el espacio que ya tiene. Estos trucos van de lo gratis (reacomodar) a lo barato (organizadores puntuales), y todos apuntan a lo mismo: mesada libre y todo a mano.',
        'secciones': [
            ("Deslizá: el antes y el después", """<div style="position:relative;max-width:640px;margin:0 auto 10px;border-radius:12px;overflow:hidden"><img src="/assets/img/blog/cocina-pequena-organizada-despues.jpg" alt="La misma cocina pequeña con la mesada despejada y todo en su lugar" width="1200" height="670" style="display:block;width:100%;height:auto"><img src="/assets/img/blog/cocina-pequena-desordenada-antes.jpg" alt="Cocina pequeña con la mesada desbordada, antes de organizarla" width="1200" height="670" style="position:absolute;inset:0;width:100%;height:auto;clip-path:inset(0 50% 0 0)"><span style="position:absolute;top:10px;left:10px;background:rgba(20,21,26,.78);color:#fff;font-size:11px;font-weight:700;padding:4px 10px;border-radius:12px;letter-spacing:1px">ANTES</span><span style="position:absolute;top:10px;right:10px;background:rgba(20,21,26,.78);color:#FFC700;font-size:11px;font-weight:700;padding:4px 10px;border-radius:12px;letter-spacing:1px">DESPUÉS</span><input type="range" min="0" max="100" value="50" aria-label="Comparar antes y después" oninput="this.parentElement.querySelectorAll('img')[1].style.clipPath='inset(0 '+(100-this.value)+'% 0 0)'" style="position:absolute;left:4%;right:4%;bottom:8px;width:92%;accent-color:#FFC700;cursor:ew-resize"></div>Deslizá para comparar: la misma cocina, con la mesada liberada y las paredes trabajando."""),
            ('La mesada es sagrada',
             'La regla número uno: la mesada es para cocinar, no para guardar. Todo lo que vive sobre la mesada tiene que ganarse el lugar. El <a href="/categoria/bazar-y-cocina/">escurridor adhesivo extraíble</a> es el ejemplo perfecto: existe cuando lo necesitás, desaparece cuando no.',
             ('prod', r'escurridor.*adhesivo|organizador escurridor')),
            ('Usá las paredes y las alturas',
             'El espacio vertical es el gran desperdiciado: <a href="/coleccion/organizadores/">organizadores colgantes</a> para tazas y utensilios, estantes sobre la bacha y ganchos bajo las alacenas. Una pared bien usada equivale a una alacena entera.',
             ('/assets/img/blog/organizador-colgante-cocina-pared.jpg', 'Organizadores colgantes de metal negro con tazas y utensilios en la pared de una cocina')),
            ('Secado inteligente',
             'Si el secaplatos clásico te come media mesada, el <a href="/categoria/bazar-y-cocina/">rack de 3 niveles regulable</a> seca la vajilla de toda la familia en la huella de un plato. Altura en vez de superficie: la lógica de toda cocina chica.',
             ('/assets/img/blog/escurridor-platos-vertical-cocina-chica.jpg', 'Escurridor de platos vertical de varios niveles junto a la bacha de una cocina pequeña')),
            ('El cajón de "todo lo demás"',
             'Toda cocina tiene un cajón caótico. Está bien — pero que sea UNO, con divisores. Cuando el caos tiene borde, no se expande.'),
            ('Las alacenas, por dentro',
             'Una alacena mal usada es 40% aire: los apilables duplican los estantes, lo pesado va abajo y lo liviano arriba, y los frascos etiquetados de frente evitan el "compré de nuevo lo que ya tenía". Regla simple: si tenés que sacar tres cosas para llegar a una, falta un organizador o sobra una cosa.',
             ('prod', r'esquinero')),
            ('Errores que achican cualquier cocina',
             'Los tres clásicos: electrodomésticos que se usan una vez al mes viviendo sobre la mesada (van adentro, salen cuando trabajan), la bolsa de bolsas sin límite (un contenedor, lo que no entra se recicla) y los tuppers sin tapa (inventario cada tres meses, sin piedad). Corregí esos tres y la cocina "crece" sin mover una pared.'),
        ],
        'faqs': [('¿Qué es lo primero para ordenar una cocina chica?',
                  'Despejar la mesada. Sacá todo lo que no uses a diario y buscale lugar en altura o pared. El cambio visual es inmediato y motiva el resto.'),
                 ('¿Los organizadores adhesivos aguantan el peso?',
                  'Los de calidad sí, sobre azulejo o superficie lisa y limpia. Cada ficha de producto indica el peso máximo recomendado.')],
    },
    'ideas-para-decorar-una-habitacion': {
        'imagen': ('/assets/img/blog/ideas-para-decorar-una-habitacion.jpg', 'Dormitorio decorado con poco presupuesto: textiles en capas, velador de luz cálida y espejo grande contra la pared'),
        'title': 'Ideas para Decorar una Habitación: 8 cambios de bajo costo | El Gadget',
        'h1': 'Ideas para decorar una habitación sin gastar de más',
        'meta': 'Ideas reales para decorar una habitación: luz cálida, espejos, textiles y detalles con personalidad. Cambios de bajo costo y alto impacto, sin obras.',
        'fecha': '2026-07-11',
        'intro': 'Decorar una habitación no arranca por comprar muebles: arranca por la luz. Después vienen los espejos, los textiles y los detalles. Estas ideas están ordenadas por impacto — las primeras transforman más por menos plata.',
        'secciones': [
            ('1. Cambiá la luz, cambia todo',
             'La luz blanca de techo mata cualquier ambiente. Un <a href="/coleccion/lamparas-y-luces-led/">velador LED cálido</a> en la mesa de luz y alguna luz indirecta crean clima al instante. Los veladores con efecto infinito espejado suman deco de día y magia de noche — por eso son los favoritos en habitaciones juveniles.',
             ('prod', r'efecto infinito')),
            ('2. Espejos: el truco de los decoradores',
             'Un <a href="/categoria/deco/">espejo decorativo</a> bien ubicado duplica la luz natural y agranda visualmente el cuarto. Frente a la ventana si querés luz; frente a la puerta, amplitud.'),
            ('3. Detalles con personalidad',
             'Una lámpara con forma divertida, un objeto de <a href="/categoria/deco/">deco</a> que te represente. La habitación genérica se vuelve tuya con dos o tres piezas elegidas, no con veinte.'),
            ('4. El orden ES deco',
             'La habitación más linda se arruina con ropa en la silla. Un <a href="/coleccion/organizadores/">organizador</a> para eso que nunca tiene lugar (el zapatero, la cajonera) es la mejora estética más subestimada.'),
            ('5. Ideas para las paredes del dormitorio',
             'La pared de la cabecera es el punto focal natural del cuarto: un espejo decorativo o una composición simple alcanzan para vestirla. En las otras paredes, menos es más — una <a href="/coleccion/lamparas-y-luces-led/">guirnalda de luz cálida</a> enmarcando una ventana da más ambiente que diez cuadros chicos peleándose la atención.',
             ('/assets/img/blog/decorar-habitacion-guirnalda-luces-led.jpg', 'Guirnalda de luces LED cálidas enmarcando la ventana de una habitación juvenil de noche')),
            ('6. Habitación infantil o juvenil: color y luz',
             'En una habitación para niñas o niños, la fórmula es color + luz con personalidad: un <a href="/coleccion/lamparas-y-luces-led/">velador con forma</a> (unicornio, flamenco, dinosaurio) que funcione como luz de compañía, y deco que puedan elegir ellos — el cuarto que sienten propio se mantiene más ordenado, comprobado por cualquier madre o padre.',
             ('/assets/img/blog/decoracion-habitacion-infantil-velador.jpg', 'Velador LED con forma de unicornio encendido en una habitación infantil serena de noche')),
        ],
        'faqs': [('¿Cómo decorar una habitación con poco presupuesto?',
                  'Prioridad: luz cálida (velador LED), un espejo y orden. Con esas tres cosas la habitación cambia más que con un mueble nuevo, y gastás una fracción.'),
                 ('¿Qué luz conviene para una habitación juvenil?',
                  'LED cálida e indirecta: veladores con diseño (efecto infinito, formas) que sumen personalidad. Evitá la luz fría de techo como única fuente.')],
    },
    'como-sacar-pelos-de-mascota-de-la-ropa': {
        'imagen': ('/assets/img/blog/como-sacar-pelos-de-perro-del-sillon.jpg', 'Perro golden retriever descansando sobre una manta clara en un sillón gris con pelos visibles'),
        'title': 'Cómo Sacar Pelos de Perro y Gato de la Ropa: 6 métodos que funcionan | El Gadget',
        'h1': 'Cómo sacar los pelos de tu mascota de la ropa (y del sillón)',
        'meta': 'Métodos probados para sacar pelos de perro y gato de la ropa, el sillón y el auto: del guante de silicona al truco del lavarropas. Y cómo prevenir.',
        'fecha': '2026-07-11',
        'intro': 'Si tenés perro o gato, los pelos son parte del outfit. Pero hay diferencia entre convivir con algunos pelos y salir de casa hecho un pulóver de angora. Estos métodos funcionan, ordenados del más rápido al más profundo — y al final, el secreto real: la prevención.',
        'secciones': [
            ('El método más rápido: guante de silicona',
             'El <a href="/categoria/accesorios-para-mascotas/">guante removedor de pelos</a> junta con una pasada lo que el rodillo de cinta tarda media hora: los pelos se adhieren a la silicona por estática y se enjuaga bajo la canilla. Sirve para ropa, sillón, manta del auto — y para cepillar directamente a tu mascota.',
             ('/assets/img/blog/guante-quita-pelos-perro-gato.jpg', 'Guante de silicona para quitar pelos de mascota cubierto de pelo de perro sobre un sillón gris')),
            ('Trucos caseros que suman',
             'Goma de látex o guante de cocina húmedo en pasadas cortas; secarropas 10 minutos con una toalla seca antes de lavar (afloja el pelo); y al lavar, media taza de vinagre blanco en el enjuague relaja las fibras y suelta el pelo pegado.'),
            ('La prevención es el 80%',
             'El pelo que no llega a la ropa no hay que sacarlo: cepillá a tu perro o gato 2-3 veces por semana con un <a href="/categoria/accesorios-para-mascotas/">cepillo o guante para el pelo</a> — en época de muda, a diario. Menos pelo suelto en el animal = menos en tu sillón.',
             ('prod', r'guante para peinar|cepillo.*mascota|guante removedor')),
            ('Bonus: la zona del comedero',
             'Donde come tu mascota se junta pelo, agua y comida. Una <a href="/categoria/accesorios-para-mascotas/">alfombra para el comedero</a> contiene el desastre en un rectángulo lavable — un truco chico que ahorra limpieza diaria.'),
            ('El protocolo del lavarropas',
             'Para que el lavarropas no redistribuya el pelo entre TODA la ropa: sacudí o pasá el guante antes de meter las prendas, lavá lo de la mascota (mantas, fundas) separado del resto, y limpiá el filtro después de cada lavado peludo. El vinagre blanco en el enjuague ayuda a que las fibras suelten lo que quedó.'),
            ('Pelos en el auto: la solución de dos minutos',
             'El tapizado del auto es velcro para el pelo de perro. El combo que funciona: manta o funda lavable en el asiento donde viaja (se sacude afuera y listo), y <a href="/categoria/accesorios-para-mascotas/">guante de silicona</a> ligeramente húmedo para las pasadas de mantenimiento en tapizados y alfombras. Dos minutos antes de devolver el auto prestado.',
             ('/assets/img/blog/quitar-pelos-de-perro-del-auto.jpg', 'Perro sentado sobre una manta protectora gris en el asiento trasero de un auto')),
        ],
        'faqs': [('¿Cómo saco los pelos de gato del sillón?',
                  'Guante de silicona ligeramente húmedo en pasadas firmes hacia un mismo lado: el pelo se junta en rollitos que levantás de una. Para tapizados delicados, aspiradora con cepillo suave antes.'),
                 ('¿Por qué mi perro larga tanto pelo?',
                  'La muda estacional (otoño y primavera) es normal. Si es excesiva fuera de temporada, consultá al veterinario: puede ser alimentación o piel. El cepillado frecuente regula la muda normal.')],
    },
}
